# Generated by Django 4.2.13 on 2024-06-26 01:14

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django_rdkit.models.fields
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apputil', '0004_alter_applicationuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chem_Structure',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('structure_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Structure ID')),
                ('structure_code', models.CharField(max_length=15, unique=True, verbose_name='Structure Code')),
                ('structure_name', models.CharField(max_length=50, unique=True, verbose_name='Structure Name')),
                ('parent_structure_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15, null=True), blank=True, null=True, size=4, verbose_name='Panel')),
                ('smol', django_rdkit.models.fields.MolField(blank=True, null=True, verbose_name='MOL')),
                ('tfp2', django_rdkit.models.fields.BfpField(null=True, verbose_name='Topological-Torsion FP')),
                ('ffp2', django_rdkit.models.fields.BfpField(null=True, verbose_name='Feature Morgan FP (FCFP)')),
                ('mfp2', django_rdkit.models.fields.BfpField(null=True, verbose_name='Morgan FP (ECFP)')),
                ('inchikey', models.CharField(blank=True, max_length=50, verbose_name='InChiKey')),
                ('mf', models.CharField(blank=True, max_length=500, verbose_name='MF')),
                ('mw', models.FloatField(blank=True, default=0, verbose_name='MW')),
                ('natoms', models.IntegerField(blank=True, default=0, verbose_name='nAtom')),
                ('nfrag', models.IntegerField(blank=True, default=0, verbose_name='nFrag')),
                ('charge', models.FloatField(blank=True, default=0, verbose_name='Charge')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('structure_class', models.ForeignKey(blank=True, db_column='structure_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_structuretype', to='apputil.dictionary', verbose_name='Type')),
            ],
            options={
                'db_table': 'chemstructure',
                'ordering': ['structure_name'],
                'indexes': [models.Index(fields=['structure_name'], name='cstruct_dname_idx'), models.Index(fields=['structure_code'], name='cstruct_dcode_idx'), models.Index(fields=['inchikey'], name='cstruct_inchi_idx'), models.Index(fields=['mf'], name='cstruct_mf_idx'), models.Index(fields=['mw'], name='cstruct_mw_idx'), models.Index(fields=['natoms'], name='cstruct_natoms_idx'), models.Index(fields=['nfrag'], name='cstruct_nfrag_idx'), models.Index(fields=['charge'], name='cstruct_charge_idx'), django.contrib.postgres.indexes.GistIndex(fields=['smol'], name='cstruct_smol_idx'), django.contrib.postgres.indexes.GistIndex(fields=['ffp2'], name='cstruct_ffp2_idx'), django.contrib.postgres.indexes.GistIndex(fields=['mfp2'], name='cstruct_mfp2_idx'), django.contrib.postgres.indexes.GistIndex(fields=['tfp2'], name='cstruct_tfp2_idx')],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='chem_structure',
            trigger=pgtrigger.compiler.Trigger(name='trigfunc_chemstruct_biu', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                                New.mfp2 := morganbv_fp(NEW.sMol);\n                                New.ffp2 := featmorganbv_fp(NEW.sMol);\n                                New.tfp2 := torsionbv_fp(NEW.sMol);\n                                New.inchikey := mol_inchikey(NEW.sMol);\n                                New.mw := mol_amw(NEW.sMol);\n                                New.mf := mol_formula(NEW.sMol);\n                                New.natoms := numheavyatoms(NEW.sMol);\n                                RETURN NEW;\n                            ', hash='ef841371660ea7d206881258eb6449bce3fb870c', operation='INSERT OR UPDATE', pgid='pgtrigger_trigfunc_chemstruct_biu_4ae21', table='chemstructure', when='BEFORE')),
        ),
    ]
