# Generated by Django 4.2.13 on 2024-06-26 01:24

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dchem', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='chem_structure',
            name='trigfunc_chemstruct_biu',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='chem_structure',
            trigger=pgtrigger.compiler.Trigger(name='trigfunc_chemstruct_biu', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                                New.mfp2 := morganbv_fp(NEW.sMol);\n                                New.ffp2 := featmorganbv_fp(NEW.sMol);\n                                New.tfp2 := torsionbv_fp(NEW.sMol);\n                                New.inchikey := mol_inchikey(NEW.sMol);\n                                New.mw := mol_amw(NEW.sMol);\n                                New.mf := mol_formula(NEW.sMol);\n                                New.natoms := mol_numheavyatoms(NEW.sMol);\n                                RETURN NEW;\n                            ', hash='52698004b361654fcf1921c58f6797102ef0bb7a', operation='INSERT OR UPDATE', pgid='pgtrigger_trigfunc_chemstruct_biu_4ae21', table='chemstructure', when='BEFORE')),
        ),
    ]
