# Generated by Django 4.2.13 on 2024-06-26 01:35

from django.db import migrations, models
import django_rdkit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dchem', '0002_remove_chem_structure_trigfunc_chemstruct_biu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chem_structure',
            name='smol',
            field=django_rdkit.models.fields.MolField(default='', verbose_name='MOL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chem_structure',
            name='structure_code',
            field=models.CharField(blank=True, max_length=15, verbose_name='Structure Code'),
        ),
        migrations.AlterField(
            model_name='chem_structure',
            name='structure_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Structure Name'),
        ),
    ]
