# Generated by Django 4.2.13 on 2024-06-26 01:44

from django.db import migrations
import django_rdkit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dchem', '0003_alter_chem_structure_smol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chem_structure',
            name='ffp2',
            field=django_rdkit.models.fields.BfpField(default='', verbose_name='Feature Morgan FP (FCFP)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chem_structure',
            name='mfp2',
            field=django_rdkit.models.fields.BfpField(default='', verbose_name='Morgan FP (ECFP)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chem_structure',
            name='tfp2',
            field=django_rdkit.models.fields.BfpField(default='', verbose_name='Topological-Torsion FP'),
            preserve_default=False,
        ),
    ]
