# Generated by Django 4.2.13 on 2024-06-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dchem', '0004_alter_chem_structure_ffp2_alter_chem_structure_mfp2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chem_structure',
            name='nfrag',
            field=models.IntegerField(blank=True, default=1, verbose_name='nFrag'),
        ),
    ]
