# Generated by Django 4.2.13 on 2024-06-26 02:10

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dchem', '0005_alter_chem_structure_nfrag'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='chem_structure',
            name='trigfunc_chemstruct_biu',
        ),
        migrations.AddField(
            model_name='chem_structure',
            name='fractioncsp3',
            field=models.FloatField(blank=True, default=0, verbose_name='Sp3'),
        ),
        migrations.AddField(
            model_name='chem_structure',
            name='hba',
            field=models.IntegerField(blank=True, default=0, verbose_name='HBond Acc'),
        ),
        migrations.AddField(
            model_name='chem_structure',
            name='hbd',
            field=models.IntegerField(blank=True, default=0, verbose_name='HBond Don'),
        ),
        migrations.AddField(
            model_name='chem_structure',
            name='logp',
            field=models.FloatField(blank=True, default=0, verbose_name='logP'),
        ),
        migrations.AddField(
            model_name='chem_structure',
            name='narorings',
            field=models.IntegerField(blank=True, default=0, verbose_name='nAroRings'),
        ),
        migrations.AddField(
            model_name='chem_structure',
            name='nhetaliphrings',
            field=models.IntegerField(blank=True, default=0, verbose_name='nHetAliphRings'),
        ),
        migrations.AddField(
            model_name='chem_structure',
            name='nhetarorings',
            field=models.IntegerField(blank=True, default=0, verbose_name='nHetAroRings'),
        ),
        migrations.AddField(
            model_name='chem_structure',
            name='nrings',
            field=models.IntegerField(blank=True, default=0, verbose_name='nRings'),
        ),
        migrations.AddField(
            model_name='chem_structure',
            name='nrotbonds',
            field=models.IntegerField(blank=True, default=0, verbose_name='nRotBond'),
        ),
        migrations.AddField(
            model_name='chem_structure',
            name='tpsa',
            field=models.FloatField(blank=True, default=0, verbose_name='tPSA'),
        ),
        migrations.AlterField(
            model_name='chem_structure',
            name='natoms',
            field=models.IntegerField(blank=True, default=0, verbose_name='nAtoms'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='chem_structure',
            trigger=pgtrigger.compiler.Trigger(name='trigfunc_chemstruct_biu', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                                New.mfp2 := morganbv_fp(NEW.sMol);\n                                New.ffp2 := featmorganbv_fp(NEW.sMol);\n                                New.tfp2 := torsionbv_fp(NEW.sMol);\n                                New.inchikey := mol_inchikey(NEW.sMol);\n                                New.mw := mol_amw(NEW.sMol);\n                                New.mf := mol_formula(NEW.sMol);\n                                New.natoms := mol_numheavyatoms(NEW.sMol);\n                                New.logp := mol_logp(NEW.sMol);\n                                New.tpsa := mol_tpsa(NEW.sMol);\n                                New.nrotbonds = mol_numrotatablebonds(NEW.sMol);\n                                New.fractioncsp3 = mol_fractioncsp3(NEW.sMol);\n                                New.hba = mol_hba(NEW.sMol);\n                                New.hbd = mol_hbd(NEW.sMol);\n                                New.nrings = mol_numrings(NEW.sMol);\n                                New.narorings = mol_numaromaticrings(NEW.sMol);\n                                New.nhetarorings = mol_numaromaticheterocycles(NEW.sMol);\n                                New.nhetaliphrings = mol_numaliphaticheterocycles(NEW.sMol);\n                                RETURN NEW;\n                            ', hash='fb4cbaefa085d17181552ac63448d346ee03495f', operation='INSERT OR UPDATE', pgid='pgtrigger_trigfunc_chemstruct_biu_4ae21', table='chemstructure', when='BEFORE')),
        ),
    ]
