# Generated by Django 4.2.13 on 2024-06-26 02:11

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dchem', '0006_remove_chem_structure_trigfunc_chemstruct_biu_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='chem_structure',
            name='trigfunc_chemstruct_biu',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='chem_structure',
            trigger=pgtrigger.compiler.Trigger(name='trigfunc_chemstruct_biu', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                                New.mfp2 := morganbv_fp(NEW.sMol);\n                                New.ffp2 := featmorganbv_fp(NEW.sMol);\n                                New.tfp2 := torsionbv_fp(NEW.sMol);\n                                New.inchikey := mol_inchikey(NEW.sMol);\n                                New.mw := mol_amw(NEW.sMol);\n                                New.mf := mol_formula(NEW.sMol);\n                                New.natoms := mol_numheavyatoms(NEW.sMol);\n                                New.logp := mol_logp(NEW.sMol);\n                                New.tpsa := mol_tpsa(NEW.sMol);\n                                New.nrotbonds = mol_numrotatablebonds(NEW.sMol);\n                                New.fractioncsp3 = mol_fractioncsp3(NEW.sMol);\n                                New.hba = mol_hba(NEW.sMol);\n                                New.hbd = mol_hbd(NEW.sMol);\n                                New.nrings = mol_numrings(NEW.sMol);\n                                New.narorings = mol_numaromaticrings(NEW.sMol);\n                                New.nhetarorings = mol_numaromaticheterocycles(NEW.sMol);\n                                New.nhetaliphrings = mol_numaliphaticheterocycles(NEW.sMol);\n                                RETURN NEW;\n                            ', hash='a972e3d94ffb850425808e4dced7a03bc414f977', operation='INSERT OR UPDATE', pgid='pgtrigger_trigfunc_chemstruct_biu_4ae21', table='chemstructure', when='BEFORE')),
        ),
    ]
