# Generated by Django 4.2.13 on 2024-06-26 06:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dchem', '0007_remove_chem_structure_trigfunc_chemstruct_biu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chem_structure',
            name='atom_classes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15, null=True), blank=True, null=True, size=4, verbose_name='Atom Classes'),
        ),
    ]
