# Generated by Django 6.0.1 on 2026-02-10 04:43

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apputil', '0005_alter_applicationuser_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collab_Group',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('group_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Group ID')),
                ('group_code', models.CharField(max_length=50, unique=True, verbose_name='Group Code')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='EMail')),
                ('department', models.CharField(blank=True, max_length=250, verbose_name='Department')),
                ('postal_address', models.CharField(blank=True, max_length=250, verbose_name='Postal Address')),
                ('city', models.CharField(blank=True, max_length=250, verbose_name='City')),
                ('country', django_countries.fields.CountryField(default='AU', max_length=2, verbose_name='Country')),
                ('pi_user_id', models.CharField(blank=True, max_length=10, verbose_name='PI ID')),
                ('mta_document', models.CharField(blank=True, max_length=150, verbose_name='MTA Document')),
                ('ora_group_id', models.CharField(blank=True, max_length=15, verbose_name='Old Group ID')),
                ('ora_pi_id', models.CharField(blank=True, max_length=15, verbose_name='Old PI ID')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('mta_status', models.ForeignKey(blank=True, db_column='mta_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mta_status', to='apputil.dictionary', verbose_name='MTA Status')),
            ],
            options={
                'db_table': 'collab_group',
            },
        ),
        migrations.CreateModel(
            name='Collab_User',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('user_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='User ID')),
                ('title', models.CharField(blank=True, max_length=15, verbose_name='Title')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='EMail')),
                ('email2', models.EmailField(blank=True, max_length=254, verbose_name='EMail 2nd')),
                ('active_email', models.SmallIntegerField(blank=True, default=0, verbose_name='Active')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('subscribed', models.BooleanField(blank=True, default=False, verbose_name='Newsletter')),
                ('portal_userid', models.CharField(blank=True, max_length=50, verbose_name='Portal UserID')),
                ('portal_pw', models.CharField(blank=True, max_length=50, verbose_name='Portal Password')),
                ('department', models.CharField(blank=True, max_length=250, verbose_name='Department')),
                ('postal_address', models.CharField(blank=True, max_length=250, verbose_name='Postal Address')),
                ('city', models.CharField(blank=True, max_length=250, verbose_name='City')),
                ('country', django_countries.fields.CountryField(default='AU', max_length=2, verbose_name='Country')),
                ('pi', models.BooleanField(default=False, verbose_name='PI')),
                ('ora_user_id', models.CharField(blank=True, max_length=15, verbose_name='Old User ID')),
                ('ora_group_id', models.CharField(blank=True, max_length=15, verbose_name='Old Group ID')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'collab_user',
            },
        ),
        migrations.CreateModel(
            name='Collab_Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LI', 'Lead Investigator'), ('M', 'Member')], default='M', max_length=2)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='dcollab.collab_group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='dcollab.collab_user')),
            ],
            options={
                'db_table': 'collab_membership',
            },
        ),
        migrations.AddField(
            model_name='collab_group',
            name='group_members',
            field=models.ManyToManyField(through='dcollab.Collab_Membership', through_fields=('group_id', 'user_id'), to='dcollab.collab_user'),
        ),
        migrations.CreateModel(
            name='Data_Source',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('data_id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Data ID')),
                ('data_name', models.CharField(blank=True, max_length=50, verbose_name='Data Name')),
                ('data_code', models.CharField(blank=True, max_length=10, verbose_name='Data Code')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Description')),
                ('journal', models.CharField(blank=True, max_length=50, verbose_name='Journal')),
                ('year', models.IntegerField(blank=True, verbose_name='Year')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='Volume')),
                ('issue', models.CharField(blank=True, max_length=50, verbose_name='Issue')),
                ('page', models.CharField(blank=True, max_length=50, verbose_name='Page')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Title')),
                ('pubmed_id', models.IntegerField(blank=True, verbose_name='PubMed ID')),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('url', models.CharField(blank=True, max_length=100, verbose_name='URL')),
                ('authors', models.CharField(blank=True, max_length=1000, verbose_name='Authors')),
                ('patent_id', models.CharField(blank=True, max_length=500, verbose_name='Patent IDs')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('data_type', models.ForeignKey(blank=True, db_column='data_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_data_type', to='apputil.dictionary', verbose_name='Data Type')),
                ('group_id', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_group_id', to='dcollab.collab_group', verbose_name='Group ID')),
            ],
            options={
                'db_table': 'data_source',
                'ordering': ['data_name', 'data_type'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('organisation_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Organisation ID')),
                ('organisation_code', models.CharField(max_length=20, unique=True, verbose_name='Organisation Code')),
                ('organisation_name', models.CharField(max_length=250, unique=True, verbose_name='Organisation')),
                ('country', django_countries.fields.CountryField(default='AU', max_length=2, verbose_name='Country')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('organisation_type', models.ForeignKey(db_column='organisation_type', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_organisation_type', to='apputil.dictionary', verbose_name='Organisation Type')),
            ],
            options={
                'db_table': 'organisation',
            },
        ),
        migrations.AddField(
            model_name='collab_user',
            name='organisation_id',
            field=models.ForeignKey(blank=True, db_column='organisation_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_organisation_id', to='dcollab.organisation', verbose_name='Organisation ID'),
        ),
        migrations.AddField(
            model_name='collab_group',
            name='organisation_id',
            field=models.ForeignKey(blank=True, db_column='organisation_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_organisation_id', to='dcollab.organisation', verbose_name='Organisation ID'),
        ),
        migrations.AddIndex(
            model_name='collab_membership',
            index=models.Index(fields=['role'], name='cmem_role_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collab_membership',
            unique_together={('user_id', 'group_id')},
        ),
        migrations.AddIndex(
            model_name='collab_user',
            index=models.Index(fields=['first_name', 'last_name'], name='cuser_name_idx'),
        ),
        migrations.AddIndex(
            model_name='collab_user',
            index=models.Index(fields=['email'], name='cuser_email_idx'),
        ),
        migrations.AddIndex(
            model_name='collab_group',
            index=models.Index(fields=['group_code'], name='cgrp_code_idx'),
        ),
        migrations.AddIndex(
            model_name='collab_group',
            index=models.Index(fields=['email'], name='cgrp_email_idx'),
        ),
    ]
