# Generated by Django 6.0.1 on 2026-03-03 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcollab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab_membership',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='dcollab.collab_group'),
        ),
        migrations.AlterField(
            model_name='collab_membership',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='dcollab.collab_user'),
        ),
    ]
