# Generated by Django 4.1.5 on 2023-04-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcollab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_source',
            name='source_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Source ID'),
        ),
    ]
