# Generated by Django 6.0.1 on 2026-03-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcollab', '0002_alter_collab_membership_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab_membership',
            name='status',
            field=models.CharField(choices=[('C', 'Current'), ('P', 'Past')], default='C', max_length=1),
        ),
        migrations.AddIndex(
            model_name='collab_membership',
            index=models.Index(fields=['status'], name='cmem_status_idx'),
        ),
    ]
