# Generated by Django 6.0.1 on 2026-03-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcollab', '0003_collab_membership_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='previous_names',
            field=models.CharField(default='', max_length=250, verbose_name='Former'),
            preserve_default=False,
        ),
    ]
