# Generated by Django 6.0.1 on 2026-03-04 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcollab', '0004_organisation_previous_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collab_group',
            name='pi_user_id',
        ),
        migrations.AddField(
            model_name='collab_group',
            name='li_user_id',
            field=models.ForeignKey(blank=True, db_column='li_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_li_user_id', to='dcollab.collab_user', verbose_name='Lead Investigator'),
        ),
    ]
