# Generated by Django 6.0.1 on 2026-05-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcollab', '0005_remove_collab_group_pi_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collab_group',
            options={'ordering': ['group_code']},
        ),
    ]
