# Generated by Django 4.1.1 on 2022-10-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaries',
            name='Dict_Value',
            field=models.CharField(max_length=50, verbose_name='Value'),
        ),
    ]
