# Generated by Django 4.1.1 on 2022-10-18 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groupfilter',
        ),
    ]
