# Generated by Django 4.1.1 on 2022-10-14 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astatus', models.IntegerField(default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(blank=True, editable=False, verbose_name='Deleted at')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('title_name', models.CharField(blank=True, max_length=15)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('short_name', models.CharField(blank=True, max_length=55)),
                ('initials', models.CharField(blank=True, max_length=5)),
                ('organisation', models.CharField(blank=True, max_length=250)),
                ('department', models.CharField(blank=True, max_length=250)),
                ('group', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('email', models.CharField(blank=True, max_length=80)),
                ('permissions', models.CharField(blank=True, max_length=250)),
                ('session_id', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'application_user',
            },
        ),
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_code', models.CharField(blank=True, editable=False, max_length=15)),
                ('log_proc', models.CharField(blank=True, editable=False, max_length=50)),
                ('log_type', models.CharField(blank=True, editable=False, max_length=15)),
                ('log_time', models.DateTimeField(auto_now=True)),
                ('log_object', models.CharField(blank=True, editable=False, max_length=15)),
                ('log_desc', models.CharField(blank=True, editable=False, max_length=1024)),
                ('log_status', models.CharField(blank=True, editable=False, max_length=15)),
                ('log_user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_log',
            },
        ),
        migrations.CreateModel(
            name='ApplicationDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astatus', models.IntegerField(default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(blank=True, editable=False, verbose_name='Deleted at')),
                ('dict_table', models.CharField(max_length=30, verbose_name='Dict Table')),
                ('dict_field', models.CharField(max_length=15, verbose_name='Dict Field')),
                ('dict_value', models.CharField(max_length=50, verbose_name='Dict Value')),
                ('dict_value_type', models.CharField(max_length=20, verbose_name='Dict Value Type')),
                ('dict_order', models.IntegerField(verbose_name='Dict Value Order')),
                ('dict_desc', models.CharField(blank=True, max_length=120, verbose_name='Dict Value Description')),
            ],
            options={
                'db_table': 'application_dictionary',
                'unique_together': {('dict_value_type', 'dict_value')},
            },
        ),
    ]
