# Generated by Django 3.2.6 on 2022-10-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
