# Generated by Django 4.1.1 on 2022-10-14 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_applicationuser_applicationlog_applicationdictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdictionary',
            name='acreated_by',
            field=models.ForeignKey(blank=True, default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationdictionary',
            name='adeleted_by',
            field=models.ForeignKey(blank=True, default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationdictionary',
            name='aupdated_by',
            field=models.ForeignKey(blank=True, default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='acreated_by',
            field=models.ForeignKey(blank=True, default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='adeleted_by',
            field=models.ForeignKey(blank=True, default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='aupdated_by',
            field=models.ForeignKey(blank=True, default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
            preserve_default=False,
        ),
    ]
