# Generated by Django 3.2.6 on 2022-10-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221031_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='user_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
