# Generated by Django 4.1.1 on 2022-10-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_applicationdictionary_acreated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdictionary',
            name='dict_order',
            field=models.IntegerField(null=True, verbose_name='Dict Value Order'),
        ),
    ]
