# Generated by Django 3.2.6 on 2022-11-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_applicationuser_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='permissions',
            field=models.CharField(choices=[('staff', 'staff| staff can edit record'), ('admin', 'admin| admin is a superuser')], default=None, max_length=250, null=True),
        ),
    ]
