# Generated by Django 4.1.1 on 2022-10-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_applicationdictionary_dict_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdictionary',
            name='dict_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dict Value Order'),
        ),
    ]
