# Generated by Django 4.1.1 on 2022-10-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_applicationdictionary_acreated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdictionary',
            name='adeleted_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='adeleted_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
        ),
    ]
