# Generated by Django 4.1.1 on 2022-10-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_applicationdictionary_adeleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationuser',
            options={'permissions': (('update', 'change data'),)},
        ),
    ]
