# Generated by Django 4.1.1 on 2022-10-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_applicationuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdictionary',
            name='astatus',
            field=models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='astatus',
            field=models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status'),
        ),
    ]
