# Generated by Django 4.1.1 on 2022-10-19 13:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django_rdkit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drugbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('drug_id', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('drug_name', models.CharField(blank=True, max_length=50, null=True)),
                ('drug_code', models.CharField(blank=True, max_length=10, null=True)),
                ('drug_synonyms', models.CharField(blank=True, max_length=1024, null=True)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('cas', models.CharField(blank=True, max_length=15, null=True)),
                ('unii', models.CharField(blank=True, max_length=15, null=True)),
                ('access_ids', models.CharField(blank=True, max_length=250, null=True)),
                ('db_access_ids', models.TextField(blank=True, null=True)),
                ('drug_mol', django_rdkit.models.fields.MolField(blank=True, null=True)),
                ('drug_smiles', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'drugbank',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organisms',
            fields=[
                ('Organism_ID', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Organism ID')),
                ('Organism_Desc', models.CharField(blank=True, default='--', max_length=512, null=True, verbose_name='Organism Description')),
                ('Strain_ID', models.CharField(blank=True, max_length=250, null=True, verbose_name='Strain ID')),
                ('Strain_Code', models.CharField(blank=True, default='--', max_length=500, null=True, verbose_name='Strain Code')),
                ('Strain_Desc', models.CharField(blank=True, default='--', max_length=512, null=True, verbose_name='Strain Description')),
                ('Strain_Notes', models.CharField(blank=True, default='--', max_length=512, null=True, verbose_name='Strain Notes')),
                ('Strain_Tissue', models.CharField(blank=True, default='--', max_length=220, null=True, verbose_name='Strain Tissue')),
                ('Sequence', models.CharField(blank=True, default='--', max_length=512, verbose_name='Sequence')),
                ('Sequence_Link', models.CharField(blank=True, default='--', max_length=1000, null=True, verbose_name='Sequence Link')),
                ('Tax_ID', models.IntegerField(default=0, null=True, verbose_name='NCBI Tax ID')),
                ('Import_Permit', models.CharField(blank=True, default='--', max_length=500, null=True, verbose_name='Import Permit')),
                ('Special_Precaution', models.CharField(blank=True, default='--', max_length=512, null=True, verbose_name='Special Precaution')),
                ('Lab_Restriction', models.CharField(blank=True, default='--', max_length=512, null=True, verbose_name='Special Precaution')),
                ('MTA_Document', models.CharField(blank=True, default='--', max_length=500, null=True, verbose_name='MTA Document')),
                ('Atmosphere_Pref', models.CharField(blank=True, max_length=500, null=True, verbose_name='Atmosphere Preference')),
                ('Nutrient_Pref', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nutirent Preference')),
                ('Biofilm_Pref', models.CharField(blank=True, max_length=500, null=True, verbose_name='Biofilm Preference')),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('Organism_Name', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='Specie')),
                ('Other_Names', models.CharField(blank=True, max_length=250, verbose_name='Other Names')),
                ('Code', models.CharField(blank=True, max_length=12, verbose_name='Code')),
                ('Tax_ID', models.IntegerField(verbose_name='NCBI Tax ID')),
                ('Parent_Tax_ID', models.IntegerField(verbose_name='NCBI Parent Tax ID')),
                ('Tax_Rank', models.CharField(blank=True, max_length=50, verbose_name='Taxonomy Rank')),
                ('Division', models.CharField(blank=True, max_length=150, null=True)),
                ('Lineage', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25, null=True), size=15)),
            ],
        ),
    ]
