# Generated by Django 4.1.1 on 2022-10-17 00:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django_rdkit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drugbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('drug_id', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('drug_name', models.CharField(blank=True, max_length=50, null=True)),
                ('drug_code', models.CharField(blank=True, max_length=10, null=True)),
                ('drug_synonyms', models.CharField(blank=True, max_length=1024, null=True)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('cas', models.CharField(blank=True, max_length=15, null=True)),
                ('unii', models.CharField(blank=True, max_length=15, null=True)),
                ('access_ids', models.CharField(blank=True, max_length=250, null=True)),
                ('db_access_ids', models.TextField(blank=True, null=True)),
                ('drug_mol', django_rdkit.models.fields.MolField(blank=True, null=True)),
                ('drug_smiles', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'drugbank',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted at')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organisms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted at')),
                ('Organism_ID', models.CharField(blank=True, max_length=100, unique=True, verbose_name='OrgID')),
                ('Organism_Name', models.CharField(blank=True, editable=False, max_length=312, unique=True, verbose_name='Organism Name')),
                ('Organism_Desc', models.CharField(blank=True, default='--', max_length=512, null=True, verbose_name='Organism Description')),
                ('Organism_Class_set', models.CharField(blank=True, max_length=500, verbose_name='Organism Class')),
                ('Strain_ID', models.CharField(blank=True, max_length=250, null=True, verbose_name='Strain ID')),
                ('Strain_Code', models.CharField(blank=True, default='--', max_length=500, null=True, verbose_name='Strain Code')),
                ('Strain_Desc', models.CharField(blank=True, default='--', max_length=512, null=True, verbose_name='Strain Description')),
                ('Strain_Notes', models.CharField(blank=True, default='--', max_length=512, null=True, verbose_name='Strain Notes')),
                ('Strain_Tissue', models.CharField(blank=True, default='--', max_length=220, null=True, verbose_name='Strain Tissue')),
                ('Strain_Type', models.CharField(blank=True, default='--', max_length=250, null=True, verbose_name='Strain Types')),
                ('Sequence', models.CharField(blank=True, default='--', max_length=512, verbose_name='Sequence')),
                ('Sequence_Link', models.CharField(blank=True, default='--', max_length=1000, null=True, verbose_name='Sequence Link')),
                ('Geno_Type', models.CharField(blank=True, default='--', max_length=512, null=True, verbose_name='GenoType')),
                ('Screen_Type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), blank=True, null=True, size=20)),
                ('Tax_ID', models.IntegerField(default=0, null=True, verbose_name='NCBI Tax ID')),
                ('Risk_Group', models.CharField(blank=True, choices=[('RG1', 'Risk Group 1'), ('RG2', 'Risk Group 2')], max_length=500, null=True, verbose_name='Risk Group')),
                ('Pathogen', models.CharField(blank=True, choices=[('PAT', 'Pathogen'), ('NOP', 'Non-Pathogen')], max_length=500, null=True, verbose_name='Risk Group')),
                ('Import_Permit', models.CharField(blank=True, default='--', max_length=500, null=True, verbose_name='Import Permit')),
                ('Biol_Approval', models.CharField(blank=True, default='--', max_length=450, null=True, verbose_name='Biological Approval')),
                ('Special_Precaution', models.CharField(blank=True, default='--', max_length=512, null=True, verbose_name='Special Precaution')),
                ('Lab_Restriction', models.CharField(blank=True, default='--', max_length=512, null=True, verbose_name='Special Precaution')),
                ('MTA_Document', models.CharField(blank=True, default='--', max_length=500, null=True, verbose_name='MTA Document')),
                ('MTA_Status', models.CharField(blank=True, default='--', max_length=500, null=True, verbose_name='MTA Status')),
                ('Oxygen_Pref', models.CharField(blank=True, max_length=500, null=True, verbose_name='Oxygen Preference')),
                ('Atmosphere_Pref', models.CharField(blank=True, max_length=500, null=True, verbose_name='Atmosphere Preference')),
                ('Nutrient_Pref', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nutirent Preference')),
                ('Biofilm_Pref', models.CharField(blank=True, max_length=500, null=True, verbose_name='Biofilm Preference')),
            ],
            options={
                'db_table': 'strain_organisms',
            },
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted at')),
                ('Organism_Name', models.CharField(max_length=150, unique=True, verbose_name='Specie')),
                ('Other_Names', models.CharField(blank=True, max_length=250, verbose_name='Other Names')),
                ('Code', models.CharField(blank=True, max_length=12, verbose_name='Code')),
                ('Class', models.CharField(blank=True, choices=[('GN', 'Gram-Negative'), ('GP', 'Gram-Positive'), ('MB', 'Mycobacteria'), ('FG', 'Fungi'), ('PL', 'Plant'), ('MA', 'Mammalian')], max_length=50, verbose_name='Class')),
                ('Tax_ID', models.IntegerField(verbose_name='NCBI Tax ID')),
                ('Parent_Tax_ID', models.IntegerField(default=468123, verbose_name='NCBI Parent Tax ID')),
                ('Tax_Rank', models.CharField(blank=True, max_length=50, verbose_name='Taxonomy Rank')),
                ('Division', models.CharField(blank=True, choices=[('ROD', 'Rodents'), ('BCT', 'Bacteria'), ('MAM', 'Mammals'), ('PLN', 'Plants and Fungi'), ('PRI', 'Primates')], max_length=25, verbose_name='Division')),
                ('Division_CODE', models.CharField(blank=True, default='PLN', max_length=25, verbose_name='Division_code')),
                ('Lineage', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), size=15)),
            ],
            options={
                'db_table': 'strain_taxonomy',
            },
        ),
    ]
