# Generated by Django 4.1.1 on 2022-10-14 00:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='Division_CODE',
            field=models.CharField(blank=True, default='PLN', max_length=25, verbose_name='Division_code'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='Lineage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), size=15),
        ),
    ]
