# Generated by Django 4.1.1 on 2022-10-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aa_chem', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='Class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dictClass+', to='app.dictionaries', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='organisms',
            name='Biol_Approval',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_requests_BA', to='app.dictionaries', verbose_name='Biological Approval'),
        ),
        migrations.AddField(
            model_name='organisms',
            name='MTA_Status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_requests_MTA', to='app.dictionaries', verbose_name='MTA Status'),
        ),
        migrations.AddField(
            model_name='organisms',
            name='Organism_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aa_chem.taxonomy', verbose_name='Organism Name'),
        ),
        migrations.AddField(
            model_name='organisms',
            name='Oxygen_Pref',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_requests_OP', to='app.dictionaries', verbose_name='Oxygen Preference'),
        ),
        migrations.AddField(
            model_name='organisms',
            name='Pathogen',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_requests_PT', to='app.dictionaries', verbose_name='Pathogen Group'),
        ),
        migrations.AddField(
            model_name='organisms',
            name='Risk_Group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_requests_RG', to='app.dictionaries', verbose_name='Risk Group'),
        ),
        migrations.AddField(
            model_name='organisms',
            name='Strain_Type',
            field=models.ManyToManyField(to='app.dictionaries'),
        ),
    ]
