# Generated by Django 4.1.1 on 2022-10-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0002_remove_drugbank_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugbank',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
