# Generated by Django 4.1.1 on 2022-10-18 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0002_alter_organisms_organism_class_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisms',
            name='Organism_Class_set',
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Organism_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aa_chem.taxonomy', to_field='Organism_Name', verbose_name='Organism Class Set'),
        ),
    ]
