# Generated by Django 4.1.1 on 2022-10-25 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('aa_chem', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='Division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_requests_Div', to='app.dictionaries', verbose_name='Division'),
        ),
    ]
