# Generated by Django 4.1.2 on 2022-10-21 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices_multi',
            name='acreated_at',
        ),
        migrations.RemoveField(
            model_name='choices_multi',
            name='acreated_by',
        ),
        migrations.RemoveField(
            model_name='choices_multi',
            name='adeleted_at',
        ),
        migrations.RemoveField(
            model_name='choices_multi',
            name='adeleted_by',
        ),
        migrations.RemoveField(
            model_name='choices_multi',
            name='astatus',
        ),
        migrations.RemoveField(
            model_name='choices_multi',
            name='aupdated_at',
        ),
        migrations.RemoveField(
            model_name='choices_multi',
            name='aupdated_by',
        ),
        migrations.RemoveField(
            model_name='genes',
            name='acreated_at',
        ),
        migrations.RemoveField(
            model_name='genes',
            name='acreated_by',
        ),
        migrations.RemoveField(
            model_name='genes',
            name='adeleted_at',
        ),
        migrations.RemoveField(
            model_name='genes',
            name='adeleted_by',
        ),
        migrations.RemoveField(
            model_name='genes',
            name='astatus',
        ),
        migrations.RemoveField(
            model_name='genes',
            name='aupdated_at',
        ),
        migrations.RemoveField(
            model_name='genes',
            name='aupdated_by',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='acreated_at',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='acreated_by',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='adeleted_at',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='adeleted_by',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='astatus',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='aupdated_at',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='aupdated_by',
        ),
    ]
