# Generated by Django 4.1.1 on 2022-10-17 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Organism_Class_set',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aa_chem.taxonomy', verbose_name='Organism Class Set'),
        ),
    ]
