# Generated by Django 4.1.1 on 2022-10-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Type',
            field=models.CharField(choices=[('CI', 'Clinical Isolate'), ('RX', 'Resistant XDR'), ('RM', 'Resistant MDR')], max_length=10),
        ),
    ]
