# Generated by Django 4.1.1 on 2022-10-26 11:23

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Type',
            field=app.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[], max_length=150, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
