# Generated by Django 4.1.1 on 2022-10-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0002_taxonomy_division_code_alter_taxonomy_lineage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genes',
            name='acreated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='genes',
            name='adeleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='genes',
            name='aupdated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='acreated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='adeleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='aupdated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='Parent_Tax_ID',
            field=models.IntegerField(default=468123, verbose_name='NCBI Parent Tax ID'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='acreated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='adeleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='aupdated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
    ]
