# Generated by Django 4.1.1 on 2022-10-17 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0003_alter_organisms_organism_class_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Organism_Class_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aa_chem.taxonomy', verbose_name='Organism Class Set'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Organism_Name',
            field=models.CharField(blank=True, editable=False, max_length=312, verbose_name='Organism Name'),
        ),
    ]
