# Generated by Django 4.1.1 on 2022-10-26 13:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0003_alter_organisms_strain_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Import_Permit',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Import Permit'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Lab_Restriction',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Special Precaution'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='MTA_Document',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='MTA Document'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Organism_Desc',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Organism Description'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Sequence',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Sequence_Link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Sequence Link'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Special_Precaution',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Special Precaution'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Strain Code'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Desc',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Strain Description'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Notes',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Strain Notes'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Tissue',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='Strain Tissue'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150, null=True), blank=True, null=True, size=20),
        ),
    ]
