# Generated by Django 4.1.2 on 2022-10-22 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aa_chem', '0003_remove_choices_multi_acreated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisms',
            name='acreated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='organisms',
            name='acreated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='organisms',
            name='adeleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='organisms',
            name='adeleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_requests_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='organisms',
            name='astatus',
            field=models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='organisms',
            name='aupdated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='organisms',
            name='aupdated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_requests_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
    ]
