# Generated by Django 4.1.1 on 2022-10-20 11:43

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0003_alter_organisms_strain_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Type',
            field=app.models.ChoiceArrayField(base_field=models.CharField(choices=[('RX', 'Resistant XDR'), ('RM', 'Resistant MDR'), ('CI', 'Clinical Isolate')], max_length=150), default=list, size=None),
        ),
    ]
