# Generated by Django 4.1.1 on 2022-10-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0003_alter_drugbank_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugbank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
