# Generated by Django 4.1.1 on 2022-10-20 12:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0004_alter_organisms_strain_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('RM', 'Resistant MDR'), ('CI', 'Clinical Isolate'), ('RX', 'Resistant XDR')], max_length=150), default=list, size=None),
        ),
    ]
