# Generated by Django 3.2.6 on 2022-10-28 04:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0004_alter_organisms_import_permit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Biol_Approval',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Biological Approval'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Lab_Restriction',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Special Precaution'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='MTA_Document',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='MTA Document'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='MTA_Status',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='MTA Status'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Organism_Desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Organism Description'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Organism_ID',
            field=models.CharField(blank=True, max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Organism ID'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Sequence',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Sequence_Link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Sequence Link'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Special_Precaution',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Special Precaution'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Strain Code'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Strain Description'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_ID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Strain ID'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Notes',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Strain Notes'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Tissue',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Strain Tissue'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=20),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='Code',
            field=models.CharField(blank=True, max_length=15, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='Organism_Name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Specie'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='Other_Names',
            field=models.CharField(blank=True, max_length=100, verbose_name='Other Names'),
        ),
    ]
