# Generated by Django 4.1.1 on 2022-10-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0004_alter_organisms_acreated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Biol_Approval',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='Biological Approval'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='MTA_Status',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='MTA Status'),
        ),
    ]
