# Generated by Django 3.2.6 on 2022-10-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0005_auto_20221028_0457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisms',
            old_name='Biol_Approval',
            new_name='Bio_Approval',
        ),
        migrations.RenameField(
            model_name='organisms',
            old_name='Pathogen',
            new_name='Pathogen_Group',
        ),
    ]
