# Generated by Django 4.1.1 on 2022-10-25 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0005_alter_organisms_biol_approval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisms',
            name='acreated_at',
        ),
        migrations.RemoveField(
            model_name='organisms',
            name='acreated_by',
        ),
        migrations.RemoveField(
            model_name='organisms',
            name='adeleted_at',
        ),
        migrations.RemoveField(
            model_name='organisms',
            name='adeleted_by',
        ),
        migrations.RemoveField(
            model_name='organisms',
            name='astatus',
        ),
        migrations.RemoveField(
            model_name='organisms',
            name='aupdated_at',
        ),
        migrations.RemoveField(
            model_name='organisms',
            name='aupdated_by',
        ),
    ]
