# Generated by Django 4.1.1 on 2022-10-24 02:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0005_taxonomy_acreated_at_taxonomy_acreated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
