# Generated by Django 4.1.1 on 2022-10-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0005_alter_genes_acreated_by_alter_genes_adeleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Organism_ID',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='OrgID'),
        ),
    ]
