# Generated by Django 4.1.1 on 2022-10-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0005_alter_organisms_strain_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Type',
            field=models.CharField(choices=[('RM', 'Resistant MDR'), ('RX', 'Resistant XDR'), ('CI', 'Clinical Isolate')], max_length=150),
        ),
    ]
