# Generated by Django 4.1.1 on 2022-10-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0006_alter_organisms_strain_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Type',
            field=models.CharField(max_length=150),
        ),
    ]
