# Generated by Django 4.1.1 on 2022-10-14 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0006_alter_organisms_organism_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='Organism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aa_chem.organisms', verbose_name='Organism_Taxo Name'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Organism_Name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Organism Name'),
        ),
    ]
