# Generated by Django 4.1.1 on 2022-10-15 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0007_taxonomy_organism_alter_organisms_organism_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomy',
            name='Organism',
        ),
        migrations.AddField(
            model_name='organisms',
            name='Organism_Name_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aa_chem.taxonomy', verbose_name='Organism Name Set'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Organism_Name',
            field=models.CharField(blank=True, editable=False, max_length=312, verbose_name='Organism Name'),
        ),
    ]
