# Generated by Django 4.1.1 on 2022-10-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0007_alter_organisms_strain_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Oxygen_Pref',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
