# Generated by Django 4.1.1 on 2022-10-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0008_remove_organisms_acreated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisms',
            options={'ordering': ['Organism_Name']},
        ),
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'ordering': ['Organism_Name']},
        ),
    ]
