# Generated by Django 4.1.1 on 2022-10-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0008_alter_organisms_strain_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
