# Generated by Django 4.1.1 on 2022-10-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0008_alter_organisms_oxygen_pref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Risk_Group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
