# Generated by Django 4.1.1 on 2022-10-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0009_alter_organisms_risk_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Pathogen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
