# Generated by Django 4.1.1 on 2022-10-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0009_alter_organisms_options_alter_taxonomy_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomy',
            name='acreated_at',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='acreated_by',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='adeleted_at',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='adeleted_by',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='astatus',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='aupdated_at',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='aupdated_by',
        ),
    ]
