# Generated by Django 4.1.1 on 2022-10-26 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_dictionaries_acreated_by_and_more'),
        ('aa_chem', '0011_taxonomy_acreated_at_taxonomy_acreated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='Class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dictClass+', to='app.dictionaries', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='Division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_Div', to='app.dictionaries', verbose_name='Division'),
        ),
    ]
