# Generated by Django 4.1.1 on 2022-10-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0011_alter_organisms_atmosphere_pref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Sequence_Link',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Sequence Link'),
        ),
    ]
