# Generated by Django 4.1.1 on 2022-10-15 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0012_alter_organisms_sequence_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Sequence_Link',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Sequence Link'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Code',
            field=models.CharField(blank=True, default=0, max_length=50, verbose_name='Strain Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Desc',
            field=models.CharField(blank=True, default=0, max_length=512, verbose_name='Strain Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_ID',
            field=models.CharField(blank=True, max_length=150, verbose_name='Strain ID'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Notes',
            field=models.CharField(blank=True, max_length=512, verbose_name='Strain Notes'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Tissue',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=120, verbose_name='Strain Tissue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Type',
            field=models.CharField(blank=True, default=0, max_length=150, verbose_name='Strain Types'),
            preserve_default=False,
        ),
    ]
