# Generated by Django 4.1.1 on 2022-10-26 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_dictionaries_acreated_by_and_more'),
        ('aa_chem', '0012_alter_taxonomy_class_alter_taxonomy_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='Division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_Divi', to='app.dictionaries', verbose_name='Division'),
        ),
    ]
