# Generated by Django 4.1.1 on 2022-10-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0013_alter_organisms_sequence_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Atmosphere_Pref',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Atmosphere Preference'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Biofilm_Pref',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Biofilm Preference'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Biol_Approval',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Biological Approval'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Import_Permit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Import Permit'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='MTA_Document',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='MTA Document'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='MTA_Status',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='MTA Status'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Nutrient_Pref',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nutirent Preference'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Oxygen_Pref',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Oxygen Preference'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Pathogen',
            field=models.CharField(blank=True, choices=[('PAT', 'Pathogen'), ('NOP', 'Non-Pathogen')], max_length=300, null=True, verbose_name='Risk Group'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Risk_Group',
            field=models.CharField(blank=True, choices=[('RG1', 'Risk Group 1'), ('RG2', 'Risk Group 2')], max_length=300, null=True, verbose_name='Risk Group'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Sequence_Link',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='Sequence Link'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Code',
            field=models.CharField(blank=True, max_length=500, verbose_name='Strain Code'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_ID',
            field=models.CharField(blank=True, max_length=250, verbose_name='Strain ID'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Tissue',
            field=models.CharField(blank=True, max_length=220, verbose_name='Strain Tissue'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Type',
            field=models.CharField(blank=True, max_length=250, verbose_name='Strain Types'),
        ),
    ]
