# Generated by Django 4.1.1 on 2022-10-26 02:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0014_organisms_acreated_at_organisms_acreated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='Lineage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25, null=True), size=25),
        ),
    ]
