# Generated by Django 4.1.1 on 2022-10-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0016_alter_organisms_atmosphere_pref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Organism_Name',
            field=models.CharField(blank=True, editable=False, max_length=312, unique=True, verbose_name='Organism Name'),
        ),
    ]
