# Generated by Django 4.1.1 on 2022-10-15 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0017_alter_organisms_organism_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Organism_Name_set',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='aa_chem.taxonomy', verbose_name='Organism Name Set'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Sequence',
            field=models.CharField(blank=True, default=0, max_length=512, verbose_name='Sequence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Sequence_Link',
            field=models.CharField(blank=True, default=0, max_length=1000, verbose_name='Sequence Link'),
            preserve_default=False,
        ),
    ]
