# Generated by Django 4.1.1 on 2022-10-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0018_alter_organisms_organism_name_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Atmosphere_Pref',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Atmosphere Preference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Biofilm_Pref',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Biofilm Preference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Biol_Approval',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Biological Approval'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Geno_Type',
            field=models.CharField(blank=True, default=0, max_length=512, verbose_name='GenoType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Import_Permit',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Import Permit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Lab_Restriction',
            field=models.CharField(blank=True, default=0, max_length=512, verbose_name='Special Precaution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisms',
            name='MTA_Document',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='MTA Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisms',
            name='MTA_Status',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='MTA Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Nutrient_Pref',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Nutirent Preference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Oxygen_Pref',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Oxygen Preference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Pathogen',
            field=models.CharField(blank=True, choices=[('PAT', 'Pathogen'), ('NOP', 'Non-Pathogen')], default=0, max_length=500, verbose_name='Risk Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Risk_Group',
            field=models.CharField(blank=True, choices=[('RG1', 'Risk Group 1'), ('RG2', 'Risk Group 2')], default=0, max_length=500, verbose_name='Risk Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Special_Precaution',
            field=models.CharField(blank=True, default=0, max_length=512, verbose_name='Special Precaution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Tax_ID',
            field=models.IntegerField(default=0, verbose_name='NCBI Tax ID'),
            preserve_default=False,
        ),
    ]
