# Generated by Django 4.1.1 on 2022-10-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0020_alter_organisms_biol_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Organism_ID',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='OrgID'),
        ),
    ]
