# Generated by Django 4.1.1 on 2022-10-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0021_alter_organisms_organism_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisms',
            name='Biol_Approval',
            field=models.CharField(blank=True, default='--', max_length=450, verbose_name='Biological Approval'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Geno_Type',
            field=models.CharField(blank=True, default='--', max_length=512, verbose_name='GenoType'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Import_Permit',
            field=models.CharField(blank=True, default='--', max_length=500, verbose_name='Import Permit'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Lab_Restriction',
            field=models.CharField(blank=True, default='--', max_length=512, verbose_name='Special Precaution'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='MTA_Document',
            field=models.CharField(blank=True, default='--', max_length=500, verbose_name='MTA Document'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='MTA_Status',
            field=models.CharField(blank=True, default='--', max_length=500, verbose_name='MTA Status'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Organism_Desc',
            field=models.CharField(blank=True, default='--', max_length=512, verbose_name='Organism Description'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Pathogen',
            field=models.CharField(blank=True, choices=[('PAT', 'Pathogen'), ('NOP', 'Non-Pathogen')], default='--', max_length=500, verbose_name='Risk Group'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Risk_Group',
            field=models.CharField(blank=True, choices=[('RG1', 'Risk Group 1'), ('RG2', 'Risk Group 2')], default='--', max_length=500, verbose_name='Risk Group'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Sequence',
            field=models.CharField(blank=True, default='--', max_length=512, verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Sequence_Link',
            field=models.CharField(blank=True, default='--', max_length=1000, verbose_name='Sequence Link'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Special_Precaution',
            field=models.CharField(blank=True, default='--', max_length=512, verbose_name='Special Precaution'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Code',
            field=models.CharField(blank=True, default='--', max_length=500, verbose_name='Strain Code'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Desc',
            field=models.CharField(blank=True, default='--', max_length=512, verbose_name='Strain Description'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_ID',
            field=models.CharField(blank=True, default='--', max_length=250, verbose_name='Strain ID'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Notes',
            field=models.CharField(blank=True, default='--', max_length=512, verbose_name='Strain Notes'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Tissue',
            field=models.CharField(blank=True, default='--', max_length=220, verbose_name='Strain Tissue'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Strain_Type',
            field=models.CharField(blank=True, default='--', max_length=250, verbose_name='Strain Types'),
        ),
    ]
