# Generated by Django 4.1.1 on 2022-10-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_chem', '0022_alter_organisms_biol_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genes',
            name='astatus',
            field=models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='astatus',
            field=models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='astatus',
            field=models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status'),
        ),
    ]
