# Generated by Django 4.2.13 on 2024-07-01 03:23

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apputil', '0004_alter_applicationuser_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dcollab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('project_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Project ID')),
                ('project_name', models.CharField(max_length=50, unique=True, verbose_name='Project Name')),
                ('owner_user', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25, null=True), blank=True, null=True, size=10, verbose_name='User')),
                ('source', models.CharField(blank=True, max_length=250, verbose_name='Source')),
                ('source_code', models.CharField(blank=True, max_length=120, verbose_name='Source Code')),
                ('reference', models.CharField(blank=True, max_length=150, verbose_name='Reference')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('owner_group', models.ForeignKey(blank=True, db_column='owner_group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_ownergroup', to='dcollab.collab_group', verbose_name='Group')),
                ('project_class', models.ForeignKey(blank=True, db_column='project_class', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_projectclass', to='apputil.dictionary', verbose_name='Class')),
            ],
            options={
                'db_table': 'project',
                'ordering': ['project_id'],
                'indexes': [models.Index(fields=['project_name'], name='prj_pname_idx')],
            },
        ),
    ]
