# Generated by Django 4.2.13 on 2024-07-03 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcollab', '0001_initial'),
        ('apputil', '0004_alter_applicationuser_options'),
        ('dsample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_class',
        ),
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.DateField(blank=True, null=True, verbose_name='Completed'),
        ),
        migrations.AddField(
            model_name='project',
            name='compound_comment',
            field=models.CharField(blank=True, max_length=150, verbose_name='Compound Comment'),
        ),
        migrations.AddField(
            model_name='project',
            name='compound_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Compound Status'),
        ),
        migrations.AddField(
            model_name='project',
            name='cpoz_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='CpOz ID'),
        ),
        migrations.AddField(
            model_name='project',
            name='data_comment',
            field=models.CharField(blank=True, max_length=150, verbose_name='Data Comment'),
        ),
        migrations.AddField(
            model_name='project',
            name='data_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Data Status'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_comment',
            field=models.CharField(blank=True, max_length=250, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(blank=True, db_column='project_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_project_type', to='apputil.dictionary', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='project',
            name='provided_comment',
            field=models.CharField(blank=True, max_length=250, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='project',
            name='provided_container',
            field=models.ForeignKey(blank=True, db_column='provided_container', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_provided_container', to='apputil.dictionary', verbose_name='Provided Container'),
        ),
        migrations.AddField(
            model_name='project',
            name='pub_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='project',
            name='pub_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Public Name'),
        ),
        migrations.AddField(
            model_name='project',
            name='pub_status',
            field=models.CharField(blank=True, max_length=10, verbose_name='Pub Status'),
        ),
        migrations.AddField(
            model_name='project',
            name='received',
            field=models.DateField(blank=True, null=True, verbose_name='Received'),
        ),
        migrations.AddField(
            model_name='project',
            name='report_comment',
            field=models.CharField(blank=True, max_length=150, verbose_name='Report Comment'),
        ),
        migrations.AddField(
            model_name='project',
            name='report_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Report Status'),
        ),
        migrations.AddField(
            model_name='project',
            name='screen_comment',
            field=models.CharField(blank=True, max_length=150, verbose_name='Screen Comment'),
        ),
        migrations.AddField(
            model_name='project',
            name='screen_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Screen Status'),
        ),
        migrations.AddField(
            model_name='project',
            name='stock_comment',
            field=models.CharField(blank=True, max_length=150, verbose_name='Stock Comment'),
        ),
        migrations.AddField(
            model_name='project',
            name='stock_conc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Stock Conc'),
        ),
        migrations.AddField(
            model_name='project',
            name='stock_conc_unit',
            field=models.ForeignKey(blank=True, db_column='stock_conc_unit', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_stock_conc_unit', to='apputil.dictionary', verbose_name='Stock Conc Unit'),
        ),
        migrations.AddField(
            model_name='project',
            name='stock_container',
            field=models.CharField(blank=True, max_length=120, verbose_name='Stock Container'),
        ),
        migrations.AddField(
            model_name='project',
            name='stock_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Stock Status'),
        ),
        migrations.AlterField(
            model_name='coadd_compound',
            name='reg_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Reg Amount'),
        ),
        migrations.AlterField(
            model_name='coadd_compound',
            name='reg_amount_unit',
            field=models.ForeignKey(blank=True, db_column='reg_amount_unit', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_reg_amount_unit', to='apputil.dictionary', verbose_name='Reg Amount Unit'),
        ),
        migrations.AlterField(
            model_name='coadd_compound',
            name='reg_conc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Reg Conc'),
        ),
        migrations.AlterField(
            model_name='coadd_compound',
            name='reg_conc_unit',
            field=models.ForeignKey(blank=True, db_column='reg_conc_unit', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_reg_conc_unit', to='apputil.dictionary', verbose_name='Reg Conc Unit'),
        ),
        migrations.AlterField(
            model_name='coadd_compound',
            name='reg_mw',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Reg MW'),
        ),
        migrations.AlterField(
            model_name='coadd_compound',
            name='reg_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Reg Volume'),
        ),
        migrations.AlterField(
            model_name='coadd_compound',
            name='reg_volume_unit',
            field=models.ForeignKey(blank=True, db_column='reg_volume_unit', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_reg_volume_unit', to='apputil.dictionary', verbose_name='Reg Volume Unit'),
        ),
        migrations.AlterField(
            model_name='coadd_compound',
            name='std_mw',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Std MW'),
        ),
        migrations.AlterField(
            model_name='coadd_compound',
            name='stock_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Stock Amount'),
        ),
        migrations.AlterField(
            model_name='coadd_compound',
            name='stock_amount_unit',
            field=models.ForeignKey(blank=True, db_column='stock_amount_unit', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_stock_amount_unit', to='apputil.dictionary', verbose_name='Stock Amount Unit'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_group',
            field=models.ForeignKey(blank=True, db_column='owner_group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_owner_group', to='dcollab.collab_group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Name'),
        ),
    ]
