# Generated by Django 4.2.13 on 2024-07-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convert_compoundid',
            name='id',
        ),
        migrations.RemoveField(
            model_name='convert_projectid',
            name='id',
        ),
        migrations.AlterField(
            model_name='convert_compoundid',
            name='ora_compound_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Old Compound ID'),
        ),
        migrations.AlterField(
            model_name='convert_projectid',
            name='ora_project_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Old Project ID'),
        ),
    ]
