# Generated by Django 6.0.1 on 2026-03-03 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcollab', '0002_alter_collab_membership_group_id_and_more'),
        ('dsample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(through='dsample.Project_Membership', through_fields=('project_id', 'user_id'), to='dcollab.collab_user'),
        ),
        migrations.AlterField(
            model_name='project_membership',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='dsample.project'),
        ),
        migrations.AlterField(
            model_name='project_membership',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='dcollab.collab_user'),
        ),
        migrations.AlterUniqueTogether(
            name='project_membership',
            unique_together={('user_id', 'project_id', 'role')},
        ),
    ]
