# Generated by Django 4.2.13 on 2024-07-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsample', '0002_coadd_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='old_project_id',
            field=models.CharField(default='P', max_length=15, unique=True, verbose_name='Old Project ID'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='coadd_sample',
            index=models.Index(fields=['std_status'], name='coadd_sst_idx'),
        ),
        migrations.AddIndex(
            model_name='coadd_sample',
            index=models.Index(fields=['pub_status'], name='coadd_pst_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['old_project_id'], name='prj_opid_idx'),
        ),
    ]
