# Generated by Django 4.2.13 on 2024-07-03 00:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsample', '0002_remove_project_project_class_project_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='compound_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=20, verbose_name='Compound Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='data_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=20, verbose_name='Data Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=20, verbose_name='Public Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='report_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=20, verbose_name='Report Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screen_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=20, verbose_name='Screen Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stock_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=20, verbose_name='Stock Status'),
        ),
    ]
