# Generated by Django 6.0.1 on 2026-03-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcollab', '0003_collab_membership_status_and_more'),
        ('dsample', '0002_project_project_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_membership',
            name='status',
            field=models.CharField(choices=[('C', 'Current'), ('P', 'Past')], default='C', max_length=1),
        ),
        migrations.AddIndex(
            model_name='project_membership',
            index=models.Index(fields=['status'], name='pmem_status_idx'),
        ),
    ]
