# Generated by Django 4.2.13 on 2024-07-03 02:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0004_alter_applicationuser_options'),
        ('dsample', '0003_alter_project_compound_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='prj_opid_idx',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='old_project_id',
            new_name='ora_project_id',
        ),
        migrations.AddField(
            model_name='project',
            name='ora_contact_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), blank=True, null=True, size=2, verbose_name='Old ContactsUser'),
        ),
        migrations.AddField(
            model_name='project',
            name='ora_group_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Old GroupID'),
        ),
        migrations.AddField(
            model_name='project',
            name='ora_hcreport_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='HC Report'),
        ),
        migrations.AddField(
            model_name='project',
            name='ora_hvreport_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='HV Report'),
        ),
        migrations.AddField(
            model_name='project',
            name='ora_organisation',
            field=models.CharField(blank=True, max_length=10, verbose_name='Old Organisation'),
        ),
        migrations.AddField(
            model_name='project',
            name='ora_psreport_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='PS Report'),
        ),
        migrations.AddField(
            model_name='project',
            name='process_status',
            field=models.CharField(blank=True, max_length=250, verbose_name='Process'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.ForeignKey(blank=True, db_column='project_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_project_status', to='apputil.dictionary', verbose_name='Project Status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['ora_project_id'], name='prj_opid_idx'),
        ),
    ]
