# Generated by Django 4.2.13 on 2024-07-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsample', '0003_project_old_project_id_coadd_sample_coadd_sst_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Project Name'),
        ),
    ]
