# Generated by Django 6.0.1 on 2026-05-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcollab', '0006_alter_collab_group_options'),
        ('dsample', '0003_project_membership_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_members', through='dsample.Project_Membership', through_fields=('project_id', 'user_id'), to='dcollab.collab_user'),
        ),
        migrations.AlterField(
            model_name='project_membership',
            name='role',
            field=models.CharField(choices=[('PC', 'Primary Contact'), ('AC', 'Alternative Contact'), ('VC', 'Virtual Contact')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='project_membership',
            name='status',
            field=models.CharField(choices=[('C', 'Current'), ('P', 'Past'), ('V', 'Virtual')], default='C', max_length=1),
        ),
    ]
