# Generated by Django 4.2.13 on 2024-07-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsample', '0004_remove_project_prj_opid_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ora_organisation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Old Organisation'),
        ),
    ]
