# Generated by Django 6.0.1 on 2026-05-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsample', '0004_alter_project_project_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ora_project_id',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Old Project ID'),
        ),
    ]
