# Generated by Django 4.2.13 on 2024-07-01 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsample', '0004_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coadd_sample',
            name='project_id',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_project_id', to='dsample.project', verbose_name='Project ID'),
        ),
    ]
