# Generated by Django 4.2.13 on 2024-07-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsample', '0005_alter_coadd_sample_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coadd_sample',
            name='prep_date',
            field=models.DateField(null=True, verbose_name='Prepared'),
        ),
    ]
