# Generated by Django 6.0.1 on 2026-06-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsample', '0005_alter_project_ora_project_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='prj_opid_idx',
        ),
        migrations.AlterField(
            model_name='project',
            name='ora_project_id',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Old Project ID'),
            preserve_default=False,
        ),
    ]
