# Generated by Django 4.2.13 on 2024-07-03 03:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsample', '0005_alter_project_ora_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='compound_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=20, verbose_name='Compound Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cpoz_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='CpOz ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stock_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=20, verbose_name='Stock Status'),
        ),
    ]
