# Generated by Django 4.2.13 on 2024-07-03 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsample', '0006_alter_project_compound_status_alter_project_cpoz_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='compound_status',
        ),
    ]
