# Generated by Django 6.0.1 on 2026-06-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsample', '0006_remove_project_prj_opid_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='abase_study_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ABase Study ID'),
        ),
    ]
