# Generated by Django 4.2.13 on 2024-07-03 03:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsample', '0007_remove_project_compound_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='compound_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=20, verbose_name='Compound Status'),
        ),
    ]
