# Generated by Django 4.2.13 on 2024-07-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsample', '0007_alter_coadd_sample_prep_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coadd_sample',
            name='pub_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Published'),
        ),
    ]
