# Generated by Django 6.0.1 on 2026-06-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsample', '0007_project_abase_study_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Project ID'),
        ),
    ]
