# Generated by Django 4.2.13 on 2024-07-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsample', '0008_alter_coadd_sample_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coadd_sample',
            name='sample_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sample Code'),
        ),
    ]
