# Generated by Django 6.0.1 on 2026-06-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsample', '0008_alter_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound_batch',
            name='full_mw',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Full MW'),
        ),
    ]
