# Generated by Django 4.2.13 on 2024-07-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsample', '0009_alter_coadd_sample_sample_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coadd_sample',
            name='sample_code',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sample Code'),
        ),
        migrations.AlterField(
            model_name='coadd_sample',
            name='sample_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Sample Name'),
        ),
    ]
