# Generated by Django 4.2.1 on 2023-07-06 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apputil', '0006_remove_image_acreated_remove_image_adeleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen_Run',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('run_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Run ID')),
                ('run_name', models.CharField(max_length=500, verbose_name='Run Name')),
                ('run_conditions', models.CharField(blank=True, max_length=250, verbose_name='Run Conditions')),
                ('run_issues', models.CharField(blank=True, max_length=250, verbose_name='Run Issues')),
                ('run_owner', models.CharField(max_length=500, verbose_name='Run Owner')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('run_status', models.ForeignKey(blank=True, db_column='run_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_RunStatus+', to='apputil.dictionary', verbose_name='Run Status')),
                ('run_type', models.ForeignKey(blank=True, db_column='run_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_RunType+', to='apputil.dictionary', verbose_name='Run Type')),
            ],
            options={
                'db_table': 'screen_run',
                'ordering': ['run_type', 'run_id'],
                'indexes': [models.Index(fields=['run_type'], name='run_type_idx')],
            },
        ),
    ]
