# Generated by Django 4.2.1 on 2023-07-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscreen', '0001_initial_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen_run',
            name='run_name',
            field=models.CharField(max_length=500, verbose_name='Run Name'),
        ),
        migrations.AlterField(
            model_name='screen_run',
            name='run_owner',
            field=models.CharField(max_length=500, verbose_name='Run Owner'),
        ),
    ]
