# Generated by Django 6.0.1 on 2026-02-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscreen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen_run',
            name='run_folder',
            field=models.CharField(blank=True, max_length=120, verbose_name='Run Name'),
        ),
    ]
