# Generated by Django 6.0.1 on 2026-03-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscreen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen_run',
            name='run_source',
            field=models.CharField(blank=True, max_length=50, verbose_name='Source'),
        ),
    ]
