# Generated by Django 4.2.1 on 2023-07-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscreen', '0001_initial_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen_run',
            name='run_date',
            field=models.DateField(blank=True, null=True, verbose_name='Run Date'),
        ),
    ]
