# Generated by Django 4.1.5 on 2023-07-12 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0001_initial'),
        ('dscreen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen_run',
            name='run_owner',
        ),
        migrations.AddField(
            model_name='screen_run',
            name='assay_note',
            field=models.CharField(blank=True, max_length=250, verbose_name='Assay Note'),
        ),
        migrations.AddField(
            model_name='screen_run',
            name='run_project',
            field=models.CharField(default='coadd', max_length=50, verbose_name='Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screen_run',
            name='run_status',
            field=models.ForeignKey(blank=True, db_column='run_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_run_status+', to='apputil.dictionary', verbose_name='Run Status'),
        ),
    ]
