# Generated by Django 6.0.1 on 2026-02-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dscreen', '0002_screen_run_run_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen_run',
            name='run_folder',
        ),
    ]
