# Generated by Django 4.1 on 2024-03-25 03:50

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apputil', '0003_alter_applicationlog_log_code_and_more'),
        ('dorganism', '0003_organism_batch_batch_quality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('cell_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Cell ID')),
                ('cell_names', models.CharField(blank=True, max_length=200, verbose_name='Cell Names')),
                ('cell_line', models.CharField(blank=True, max_length=200, verbose_name='Cell Line')),
                ('cell_notes', models.CharField(blank=True, max_length=1024, verbose_name='Cell Notes')),
                ('cell_code', models.CharField(blank=True, max_length=30, verbose_name='Cell Code')),
                ('cell_panel', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=20, verbose_name='Panel')),
                ('cell_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=20, verbose_name='Type')),
                ('cell_identification', models.CharField(blank=True, max_length=512, verbose_name='Cell Identification')),
                ('cell_origin', models.CharField(blank=True, max_length=512, verbose_name='Origin of Cell')),
                ('source', models.CharField(blank=True, max_length=250, verbose_name='Source')),
                ('source_code', models.CharField(blank=True, max_length=120, verbose_name='Source Code')),
                ('reference', models.CharField(blank=True, max_length=150, verbose_name='Reference')),
                ('mta_document', models.CharField(blank=True, max_length=150, verbose_name='MTA Document')),
                ('mta_notes', models.CharField(blank=True, max_length=512, verbose_name='MTA Notes')),
                ('collect_tissue', models.CharField(blank=True, max_length=120, verbose_name='From Tissue/Organ')),
                ('patient_diagnosis', models.CharField(blank=True, max_length=120, verbose_name='Patient Diagnosis')),
                ('patient', models.CharField(blank=True, max_length=20, verbose_name='Patient Info')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('assoc_documents', models.ManyToManyField(blank=True, db_table='org_doc', related_name='%(class)s_document', to='apputil.document', verbose_name='Douments')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('biologist', models.ForeignKey(blank=True, db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist')),
                ('mta_status', models.ForeignKey(blank=True, db_column='mta_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mta', to='apputil.dictionary', verbose_name='MTA Status')),
                ('organism_name', models.ForeignKey(db_column='organism_name', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_organism_name', to='dorganism.taxonomy', verbose_name='Organism Name')),
            ],
            options={
                'db_table': 'cell',
            },
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['cell_line'], name='cell_line_idx'),
        ),
    ]
