# Generated by Django 4.1 on 2024-03-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0003_alter_applicationlog_log_code_and_more'),
        ('dcell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='assoc_documents',
            field=models.ManyToManyField(blank=True, db_table='cell_doc', related_name='%(class)s_document', to='apputil.document', verbose_name='Douments'),
        ),
    ]
