# Generated by Django 4.1 on 2024-04-04 02:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0003_alter_applicationlog_log_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dcell', '0002_alter_cell_assoc_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell_Batch',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('cellbatch_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='CellBatch ID')),
                ('previous_batch_id', models.CharField(max_length=20, verbose_name='Previous CellBatch ID')),
                ('passage_number', models.CharField(max_length=20, verbose_name='Passage Number')),
                ('batch_id', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='Batch ID')),
                ('batch_notes', models.CharField(blank=True, max_length=500, verbose_name='Batch Notes')),
                ('quality_source', models.CharField(blank=True, max_length=150, verbose_name='QC Source')),
                ('qc_record', models.CharField(blank=True, max_length=150, verbose_name='QC Records')),
                ('stock_date', models.DateField(blank=True, null=True, verbose_name='Stock Date')),
                ('stock_level', models.CharField(blank=True, max_length=20, verbose_name='Stock Levels')),
            ],
            options={
                'db_table': 'cellbatch',
                'ordering': ['cellbatch_id'],
            },
        ),
        migrations.CreateModel(
            name='CellBatch_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('n_created', models.IntegerField(default=0, verbose_name='#Created')),
                ('n_left', models.IntegerField(default=0, verbose_name='#Left')),
                ('stock_date', models.DateField(blank=True, null=True, verbose_name='Stock Date')),
                ('stock_note', models.CharField(blank=True, max_length=10, verbose_name='Stock Note')),
                ('location_freezer', models.CharField(blank=True, max_length=80, verbose_name='Freezer')),
                ('location_rack', models.CharField(blank=True, max_length=10, verbose_name='Rack')),
                ('location_column', models.CharField(blank=True, max_length=10, verbose_name='Column')),
                ('location_slot', models.CharField(blank=True, max_length=10, verbose_name='Slot')),
            ],
            options={
                'db_table': 'cellbatch_stock',
                'ordering': ['cellbatch_id', 'stock_type'],
            },
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['cell_code'], name='cell_cellcode_idx'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['cell_type'], name='cell_celltype_idx'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['cell_panel'], name='cell_cellpanel_idx'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['source'], name='cell_source_idx'),
        ),
        migrations.AddField(
            model_name='cellbatch_stock',
            name='acreated',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='cellbatch_stock',
            name='adeleted',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='cellbatch_stock',
            name='aupdated',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='cellbatch_stock',
            name='biologist',
            field=models.ForeignKey(blank=True, db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AddField(
            model_name='cellbatch_stock',
            name='cellbatch_id',
            field=models.ForeignKey(db_column='cellbatch_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_cellbatch_id', to='dcell.cell_batch', verbose_name='CellBatch ID'),
        ),
        migrations.AddField(
            model_name='cellbatch_stock',
            name='stock_type',
            field=models.ForeignKey(db_column='stock_type', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_stock', to='apputil.dictionary', verbose_name='Stock Type'),
        ),
        migrations.AddField(
            model_name='cell_batch',
            name='acreated',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='cell_batch',
            name='adeleted',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='cell_batch',
            name='aupdated',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='cell_batch',
            name='batch_quality',
            field=models.ForeignKey(blank=True, db_column='batch_quality', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_batchquality', to='apputil.dictionary', verbose_name='Quality'),
        ),
        migrations.AddField(
            model_name='cell_batch',
            name='biologist',
            field=models.ForeignKey(blank=True, db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AddField(
            model_name='cell_batch',
            name='cell_id',
            field=models.ForeignKey(db_column='cell_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_cell_id', to='dcell.cell', verbose_name='Cell ID'),
        ),
        migrations.AddField(
            model_name='cell_batch',
            name='qc_status',
            field=models.ForeignKey(blank=True, db_column='qc_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_qc', to='apputil.dictionary', verbose_name='QC status'),
        ),
        migrations.AddIndex(
            model_name='cellbatch_stock',
            index=models.Index(fields=['stock_type'], name='cellbstock_stype_idx'),
        ),
        migrations.AddIndex(
            model_name='cellbatch_stock',
            index=models.Index(fields=['location_freezer'], name='cellbstock_freezer_idx'),
        ),
        migrations.AddIndex(
            model_name='cellbatch_stock',
            index=models.Index(fields=['stock_date'], name='cellbstock_stdate_idx'),
        ),
        migrations.AddIndex(
            model_name='cellbatch_stock',
            index=models.Index(fields=['n_left'], name='cellbstock_nleft_idx'),
        ),
        migrations.AddIndex(
            model_name='cell_batch',
            index=models.Index(fields=['cell_id', 'batch_id'], name='cellbatch_cellbatch_idx'),
        ),
        migrations.AddIndex(
            model_name='cell_batch',
            index=models.Index(fields=['qc_status'], name='cellbatch_qc_idx'),
        ),
        migrations.AddIndex(
            model_name='cell_batch',
            index=models.Index(fields=['stock_date'], name='cellbatch_sdate_idx'),
        ),
        migrations.AddIndex(
            model_name='cell_batch',
            index=models.Index(fields=['stock_level'], name='cellbatch_slevel_idx'),
        ),
    ]
