# Generated by Django 4.2.1 on 2023-07-06 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dscreen', '0002_alter_screen_run_run_name_alter_screen_run_run_owner'),
        ('dorganism', '0016_alter_orgbatch_image_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dgene', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genome_Sequence',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('seq_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Seq ID')),
                ('seq_type', models.CharField(max_length=120, verbose_name='Type')),
                ('strain_ids', models.CharField(blank=True, max_length=200, verbose_name='Strain IDs')),
                ('source', models.CharField(blank=True, max_length=250, verbose_name='Source')),
                ('source_code', models.CharField(blank=True, max_length=120, verbose_name='Source Code')),
                ('source_link', models.CharField(blank=True, max_length=120, verbose_name='Source Link')),
                ('reference', models.CharField(blank=True, max_length=150, verbose_name='Reference')),
            ],
            options={
                'db_table': 'genome_seq',
                'ordering': ['seq_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='wgs_checkm',
            options={'ordering': ['orgbatch_id', 'seq_id']},
        ),
        migrations.AlterModelOptions(
            name='wgs_fastqc',
            options={'ordering': ['orgbatch_id', 'seq', 'seq_id']},
        ),
        migrations.RemoveIndex(
            model_name='id_sequence',
            name='idseq_runid_idx',
        ),
        migrations.RemoveIndex(
            model_name='wgs_checkm',
            name='checkqc_runid_idx',
        ),
        migrations.RemoveIndex(
            model_name='wgs_fastqc',
            name='fastqc_runid_idx',
        ),
        migrations.RemoveField(
            model_name='id_sequence',
            name='run_id',
        ),
        migrations.RemoveField(
            model_name='wgs_checkm',
            name='run_id',
        ),
        migrations.RemoveField(
            model_name='wgs_fastqc',
            name='run_id',
        ),
        migrations.AddIndex(
            model_name='id_sequence',
            index=models.Index(fields=['seq_id'], name='idseq_seqid_idx'),
        ),
        migrations.AddIndex(
            model_name='wgs_checkm',
            index=models.Index(fields=['seq_id'], name='checkqc_seqid_idx'),
        ),
        migrations.AddIndex(
            model_name='wgs_fastqc',
            index=models.Index(fields=['seq_id'], name='fastqc_seqid_idx'),
        ),
        migrations.AddField(
            model_name='genome_sequence',
            name='acreated',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='genome_sequence',
            name='adeleted',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='genome_sequence',
            name='aupdated',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='genome_sequence',
            name='organism_id',
            field=models.ForeignKey(blank=True, db_column='organism_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_organism_id', to='dorganism.organism', verbose_name='Organism ID'),
        ),
        migrations.AddField(
            model_name='genome_sequence',
            name='organism_name',
            field=models.ForeignKey(blank=True, db_column='organism_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_organism_name', to='dorganism.taxonomy', verbose_name='Organism Name'),
        ),
        migrations.AddField(
            model_name='genome_sequence',
            name='orgbatch_id',
            field=models.ForeignKey(blank=True, db_column='orgbatch_id', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_orgbatch_id', to='dorganism.organism_batch', verbose_name='OrgBatch ID'),
        ),
        migrations.AddField(
            model_name='genome_sequence',
            name='run_id',
            field=models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_run_id', to='dscreen.screen_run', verbose_name='Run ID'),
        ),
        migrations.AddField(
            model_name='id_sequence',
            name='seq_id',
            field=models.ForeignKey(db_column='seq_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_seq_id', to='dgene.genome_sequence', verbose_name='Seq ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wgs_checkm',
            name='seq_id',
            field=models.ForeignKey(db_column='seq_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)seq_id', to='dgene.genome_sequence', verbose_name='Seq ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wgs_fastqc',
            name='seq_id',
            field=models.ForeignKey(db_column='seq_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)seq_id', to='dgene.genome_sequence', verbose_name='Seq ID'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='genome_sequence',
            index=models.Index(fields=['seq_id'], name='genoseq_seqid_idx'),
        ),
    ]
