# Generated by Django 4.2.2 on 2023-09-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgene', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='amr_subclass',
            field=models.CharField(blank=True, max_length=150, verbose_name='AMR Subclass'),
        ),
    ]
