# Generated by Django 4.1.5 on 2023-04-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgene', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='urlname',
        ),
    ]
