# Generated by Django 4.2.2 on 2023-09-22 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0002_alter_applicationuser_options'),
        ('dgene', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='gene_type',
            field=models.ForeignKey(blank=True, db_column='gene_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_genetype', to='apputil.dictionary', verbose_name='Gene Type'),
        ),
    ]
