# Generated by Django 6.0.1 on 2026-03-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgene', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='genome_sequence',
            name='genoseq_seqnm_idx',
        ),
        migrations.RenameField(
            model_name='genome_sequence',
            old_name='seq_name',
            new_name='runsample_name',
        ),
        migrations.AddField(
            model_name='genome_sequence',
            name='runsample_dir',
            field=models.CharField(blank=True, max_length=250, verbose_name='RunFolder'),
        ),
        migrations.AddField(
            model_name='genome_sequence',
            name='runsample_file',
            field=models.CharField(blank=True, max_length=250, verbose_name='RunFile'),
        ),
        migrations.AlterField(
            model_name='genome_sequence',
            name='seq_files',
            field=models.CharField(choices=[('Reads', 'Raw reads'), ('FastQ', 'Fastq files (trimmed)'), ('FastA', 'Fasta files (assembly)')], default='Reads', max_length=6, verbose_name='Files'),
        ),
        migrations.RemoveField(
            model_name='genome_sequence',
            name='seq_date',
        ),
    ]
