# Generated by Django 4.2.2 on 2023-09-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgene', '0002_alter_gene_gene_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amr_genotype',
            name='closest_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='AMR Method'),
        ),
    ]
