# Generated by Django 6.0.1 on 2026-03-16 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0005_alter_applicationuser_department_and_more'),
        ('dgene', '0002_remove_genome_sequence_genoseq_seqnm_idx_and_more'),
        ('dorganism', '0001_initial'),
        ('dscreen', '0002_screen_run_run_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='genome_sequence',
            name='seq_code',
            field=models.CharField(blank=True, max_length=120, unique=True, verbose_name='Seq Code'),
        ),
        migrations.AddIndex(
            model_name='genome_sequence',
            index=models.Index(fields=['seq_code'], name='genoseq_seqcd_idx'),
        ),
    ]
