# Generated by Django 4.1.5 on 2023-05-03 01:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgene', '0002_remove_gene_urlname'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='id_pub',
            name='idp_org_idx',
        ),
        migrations.RemoveField(
            model_name='id_pub',
            name='id_organism',
        ),
        migrations.AddField(
            model_name='id_pub',
            name='id_method',
            field=models.CharField(blank=True, max_length=25, verbose_name='Method'),
        ),
        migrations.AddField(
            model_name='id_pub',
            name='id_notes',
            field=models.CharField(blank=True, max_length=120, verbose_name='ID Notes'),
        ),
        migrations.AddField(
            model_name='id_pub',
            name='id_organisms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=20, verbose_name='Organisms'),
        ),
        migrations.AlterField(
            model_name='id_pub',
            name='id_date',
            field=models.DateField(blank=True, null=True, verbose_name='ID Date'),
        ),
        migrations.AlterField(
            model_name='id_sequence',
            name='id_date',
            field=models.DateField(blank=True, null=True, verbose_name='ID Date'),
        ),
        migrations.AddIndex(
            model_name='id_pub',
            index=models.Index(fields=['id_organisms'], name='idp_org_idx'),
        ),
    ]
