# Generated by Django 4.2.2 on 2023-09-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgene', '0003_alter_gene_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='gene_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Gene Name'),
        ),
    ]
