# Generated by Django 6.0.1 on 2026-03-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgene', '0003_genome_sequence_seq_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome_sequence',
            name='runsample_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='RunName'),
        ),
    ]
