# Generated by Django 4.2.2 on 2023-09-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgene', '0003_alter_amr_genotype_closest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amr_genotype',
            name='amr_method',
            field=models.CharField(blank=True, max_length=25, verbose_name='AMR Method'),
        ),
        migrations.AlterField(
            model_name='amr_genotype',
            name='closest_id',
            field=models.CharField(blank=True, max_length=25, verbose_name='AMR Method'),
        ),
        migrations.AlterField(
            model_name='amr_genotype',
            name='closest_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='AMR Method'),
        ),
        migrations.AlterField(
            model_name='amr_genotype',
            name='seq_method',
            field=models.CharField(blank=True, max_length=25, verbose_name='Seq Method'),
        ),
    ]
