# Generated by Django 6.0.1 on 2026-03-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgene', '0004_alter_genome_sequence_runsample_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome_sequence',
            name='seq_files',
            field=models.CharField(blank=True, default='Reads', max_length=50, verbose_name='Files'),
        ),
    ]
