# Generated by Django 4.2.2 on 2023-09-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgene', '0004_alter_gene_gene_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='gene_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Gene Name'),
        ),
    ]
