# Generated by Django 6.0.1 on 2026-03-23 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0005_alter_applicationuser_department_and_more'),
        ('dgene', '0005_alter_genome_sequence_seq_files'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='id_sequence',
            name='seq_filetype',
            field=models.ForeignKey(blank=True, db_column='seq_filetype', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_seqfiletype', to='apputil.dictionary', verbose_name='Seq FType'),
        ),
        migrations.AddIndex(
            model_name='id_sequence',
            index=models.Index(fields=['seq_filetype'], name='idseq_seqftype_idx'),
        ),
    ]
