# Generated by Django 6.0.1 on 2026-03-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgene', '0006_id_sequence_seq_filetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome_sequence',
            name='seq_status',
            field=models.CharField(blank=True, default='Reads', max_length=120, verbose_name='Files'),
        ),
    ]
