# Generated by Django 4.2.2 on 2023-09-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgene', '0007_alter_gene_gene_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amr_genotype',
            name='closest_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='Closest'),
        ),
    ]
