# Generated by Django 6.0.1 on 2026-03-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgene', '0007_genome_sequence_seq_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='id_sequence',
            name='idseq_seqfile_idx',
        ),
        migrations.AlterField(
            model_name='id_sequence',
            name='seq_file',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Seq File'),
            preserve_default=False,
        ),
    ]
