# Generated by Django 6.0.1 on 2026-04-03 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgene', '0008_remove_id_sequence_idseq_seqfile_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wgs_checkm',
            name='checkqc_ass_idx',
        ),
        migrations.RemoveIndex(
            model_name='wgs_checkm',
            name='checkqc_fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='wgs_checkm',
            name='checkqc_qc_idx',
        ),
        migrations.AddField(
            model_name='wgs_checkm',
            name='assembler',
            field=models.CharField(blank=True, max_length=25, verbose_name='Assembler'),
        ),
        migrations.AddField(
            model_name='wgs_checkm',
            name='checkm_status',
            field=models.CharField(blank=True, max_length=60, verbose_name='CheckM Status'),
        ),
        migrations.AddField(
            model_name='wgs_checkm',
            name='fasta_file',
            field=models.CharField(blank=True, max_length=60, verbose_name='Fasta File'),
        ),
        migrations.AddField(
            model_name='wgs_checkm',
            name='fasta_type',
            field=models.CharField(blank=True, max_length=25, verbose_name='Fasta Ttype'),
        ),
        migrations.AddIndex(
            model_name='wgs_checkm',
            index=models.Index(fields=['assembler'], name='checkqc_ass_idx'),
        ),
        migrations.AddIndex(
            model_name='wgs_checkm',
            index=models.Index(fields=['fasta_type'], name='checkqc_fa_idx'),
        ),
        migrations.AddIndex(
            model_name='wgs_checkm',
            index=models.Index(fields=['genome_size'], name='checkqc_gs_idx'),
        ),
        migrations.AddIndex(
            model_name='wgs_checkm',
            index=models.Index(fields=['checkm_status'], name='checkqc_qc_idx'),
        ),
        migrations.RemoveField(
            model_name='wgs_checkm',
            name='assembly',
        ),
        migrations.RemoveField(
            model_name='wgs_checkm',
            name='assembly_qc',
        ),
        migrations.RemoveField(
            model_name='wgs_checkm',
            name='fasta',
        ),
    ]
