# Generated by Django 6.0.1 on 2026-05-05 00:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0005_alter_applicationuser_department_and_more'),
        ('dgene', '0009_remove_wgs_checkm_checkqc_ass_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='id_sequence',
            name='serotype',
            field=models.CharField(blank=True, max_length=50, verbose_name='Serotype'),
        ),
        migrations.AddField(
            model_name='id_sequence',
            name='serotype_program',
            field=models.CharField(blank=True, max_length=50, verbose_name='Serotype Tool'),
        ),
        migrations.AddIndex(
            model_name='id_sequence',
            index=models.Index(fields=['mlst_seqtype'], name='idseq_seqt_idx'),
        ),
        migrations.AddIndex(
            model_name='id_sequence',
            index=models.Index(fields=['serotype'], name='idseq_sero_idx'),
        ),
    ]
