# Generated by Django 6.0.1 on 2026-05-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgene', '0010_id_sequence_serotype_id_sequence_serotype_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amr_genotype',
            name='closest_id',
        ),
        migrations.RemoveField(
            model_name='amr_genotype',
            name='closest_name',
        ),
        migrations.RemoveField(
            model_name='amr_genotype',
            name='seq_coverage',
        ),
        migrations.RemoveField(
            model_name='amr_genotype',
            name='seq_identity',
        ),
        migrations.AddField(
            model_name='amr_genotype',
            name='ref_coverage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Ref Coverage'),
        ),
        migrations.AddField(
            model_name='amr_genotype',
            name='ref_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ref ID'),
        ),
        migrations.AddField(
            model_name='amr_genotype',
            name='ref_identity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Ref Identity'),
        ),
        migrations.AddField(
            model_name='amr_genotype',
            name='ref_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ref Name'),
        ),
    ]
