# Generated by Django 6.0.1 on 2026-05-05 08:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgene', '0011_remove_amr_genotype_closest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome_sequence',
            name='seq_status',
            field=models.CharField(blank=True, default='Reads', max_length=250, verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='id_sequence',
            name='kraken_organisms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, null=True, size=20, verbose_name='Kraken2 Organisms'),
        ),
    ]
