# Generated by Django 6.0.1 on 2026-05-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgene', '0012_alter_genome_sequence_seq_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id_sequence',
            name='mlst_scheme',
            field=models.CharField(blank=True, max_length=50, verbose_name='MLST Scheme'),
        ),
    ]
