# Generated by Django 6.0.1 on 2026-05-18 04:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgene', '0013_alter_id_sequence_mlst_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='amr_class',
            field=models.CharField(blank=True, max_length=250, verbose_name='AMR Class'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='genbank',
            field=models.CharField(blank=True, max_length=150, verbose_name='GenBank'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='gene_modification',
            field=models.CharField(max_length=250, verbose_name='Modification'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='gene_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gene Name'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='organisms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=120, null=True), blank=True, null=True, size=10, verbose_name='Organisms'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='protein_class',
            field=models.CharField(blank=True, max_length=250, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='protein_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Protein'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='protein_subclass',
            field=models.CharField(blank=True, max_length=250, verbose_name='SubClass'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='resistance_class',
            field=models.CharField(blank=True, max_length=250, verbose_name='Resistance Class'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='uniprot',
            field=models.CharField(blank=True, max_length=150, verbose_name='UniProt'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='variants',
            field=models.CharField(blank=True, max_length=250, verbose_name='Variants'),
        ),
    ]
