# Generated by Django 3.2.6 on 2022-11-16 06:14

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apputil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted at')),
                ('Organism_Name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Specie')),
                ('Other_Names', models.CharField(blank=True, max_length=100, verbose_name='Other Names')),
                ('Code', models.CharField(blank=True, max_length=15, verbose_name='Code')),
                ('Tax_ID', models.IntegerField(verbose_name='NCBI Tax ID')),
                ('Parent_Tax_ID', models.IntegerField(verbose_name='NCBI Parent Tax ID')),
                ('Tax_Rank', models.CharField(blank=True, max_length=50, verbose_name='Taxonomy Rank')),
                ('Lineage', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25, null=True), size=25)),
                ('Class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dictClass+', to='apputil.dictionaries', verbose_name='Class')),
                ('Division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests_Div', to='apputil.dictionaries', verbose_name='Division')),
                ('acreated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taxonomy_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taxonomy_requests_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taxonomy_requests_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['Organism_Name'],
            },
        ),
        migrations.CreateModel(
            name='Organisms',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted at')),
                ('Organism_ID', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Organism ID')),
                ('Organism_Desc', models.CharField(blank=True, max_length=150, null=True, verbose_name='Organism Description')),
                ('Strain_ID', models.CharField(blank=True, max_length=50, null=True, verbose_name='Strain ID')),
                ('Strain_Code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Strain Code')),
                ('Strain_Desc', models.CharField(blank=True, max_length=150, null=True, verbose_name='Strain Description')),
                ('Strain_Notes', models.CharField(blank=True, max_length=250, null=True, verbose_name='Strain Notes')),
                ('Strain_Tissue', models.CharField(blank=True, max_length=250, null=True, verbose_name='Strain Tissue')),
                ('Strain_Type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=20)),
                ('Sequence', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sequence')),
                ('Sequence_Link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sequence Link')),
                ('Tax_ID', models.IntegerField(default=0, null=True, verbose_name='NCBI Tax ID')),
                ('Risk_Group', models.CharField(blank=True, max_length=50, null=True)),
                ('Pathogen_Group', models.CharField(blank=True, max_length=50, null=True)),
                ('Import_Permit', models.CharField(blank=True, max_length=500, null=True, verbose_name='Import Permit')),
                ('Bio_Approval', models.CharField(blank=True, max_length=200, null=True, verbose_name='Biological Approval')),
                ('Special_Precaution', models.CharField(blank=True, max_length=500, null=True, verbose_name='Special Precaution')),
                ('Lab_Restriction', models.CharField(blank=True, max_length=500, null=True, verbose_name='Special Precaution')),
                ('MTA_Document', models.CharField(blank=True, max_length=150, null=True, verbose_name='MTA Document')),
                ('MTA_Status', models.CharField(blank=True, max_length=150, null=True, verbose_name='MTA Status')),
                ('Oxygen_Pref', models.CharField(blank=True, max_length=250, null=True)),
                ('Atmosphere_Pref', models.CharField(blank=True, max_length=500, null=True, verbose_name='Atmosphere Preference')),
                ('Nutrient_Pref', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nutirent Preference')),
                ('Biofilm_Pref', models.CharField(blank=True, max_length=500, null=True, verbose_name='Biofilm Preference')),
                ('Organism_Name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dorganism.taxonomy', verbose_name='Organism Name')),
                ('acreated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organisms_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organisms_requests_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organisms_requests_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['Organism_Name'],
            },
        ),
    ]
