# Generated by Django 3.2.6 on 2022-11-17 06:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism_batch',
            name='Stock_Level',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, editable=False, null=True, size=3, verbose_name='Stock Levels'),
        ),
    ]
