# Generated by Django 3.2.6 on 2022-11-16 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dOrganism', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drugbank',
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Organism_ID',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Organism ID'),
        ),
        migrations.AlterField(
            model_name='organisms',
            name='Organism_Name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='dOrganism.taxonomy', verbose_name='Organism Name'),
            preserve_default=False,
        ),
    ]
