# Generated by Django 4.2.2 on 2023-09-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organism',
            options={},
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='n_created',
            field=models.IntegerField(default=0, verbose_name='#Created'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='n_left',
            field=models.IntegerField(default=0, verbose_name='#Left'),
        ),
    ]
