# Generated by Django 3.2.6 on 2022-12-06 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0002_auto_20221205_1616'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dorganism', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organism',
            options={},
        ),
        migrations.AlterField(
            model_name='organism',
            name='biologist',
            field=models.ForeignKey(db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_Biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='mta_status',
            field=models.ForeignKey(blank=True, db_column='mta_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_MTA+', to='apputil.dictionary', verbose_name='MTA Status'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='organism_name',
            field=models.ForeignKey(db_column='organism_name', on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_name+', to='dorganism.taxonomy', verbose_name='Organism Name'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='oxygen_pref',
            field=models.ForeignKey(blank=True, db_column='oxygen_pref', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_Oxygen+', to='apputil.dictionary', verbose_name='Oxygen'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='pathogen_group',
            field=models.ForeignKey(blank=True, db_column='pathogen_group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_Pathogen+', to='apputil.dictionary', verbose_name='Pathogen'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='risk_group',
            field=models.ForeignKey(blank=True, db_column='risk_group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_Risk+', to='apputil.dictionary', verbose_name='Risk Group'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='strain_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Strain Code'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='batch_no',
            field=models.IntegerField(default=0, verbose_name='Batch No'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='biologist',
            field=models.ForeignKey(db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_batch_Biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='organism_id',
            field=models.ForeignKey(db_column='organism_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_batch_organism_id+', to='dorganism.organism', verbose_name='Organism ID'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='biologist',
            field=models.ForeignKey(db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_culture_Biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='organism_id',
            field=models.ForeignKey(db_column='organism_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_culture_organism_id+', to='dorganism.organism', verbose_name='Organism ID'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='biologist',
            field=models.ForeignKey(db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orgbatch_stock_Biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='orgbatch_id',
            field=models.ForeignKey(db_column='orgbatch', on_delete=django.db.models.deletion.DO_NOTHING, related_name='orgbatch_stock_orgbatch_id+', to='dorganism.organism_batch', verbose_name='OrgBatch ID'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='passage_no',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Passage No'),
        ),
    ]
