# Generated by Django 4.1.3 on 2023-05-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='gen_property',
            field=models.CharField(blank=True, max_length=512, verbose_name='Genetic Property'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='res_property',
            field=models.CharField(blank=True, max_length=512, verbose_name='Susceptibility '),
        ),
        migrations.AlterField(
            model_name='organism',
            name='strain_notes',
            field=models.CharField(blank=True, max_length=512, verbose_name='Strain Notes'),
        ),
    ]
