# Generated by Django 3.2.6 on 2022-12-05 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apputil', '0003_auto_20221130_1010'),
        ('dorganism', '0002_auto_20221130_1010'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organism',
            name='org_stid_idx',
        ),
        migrations.RemoveIndex(
            model_name='organism',
            name='org_stother_idx',
        ),
        migrations.RemoveIndex(
            model_name='organism',
            name='org_mta_idx',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='atmosphere_pref',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='bio_approval',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='biofilm_pref',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='import_permit',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='nutrient_pref',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='special_precaution',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='strain_id',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='strain_otherids',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='strain_property',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='strain_tissue',
        ),
        migrations.AddField(
            model_name='organism',
            name='gen_property',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Genetic Property'),
        ),
        migrations.AddField(
            model_name='organism',
            name='growth_preference',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Growth/Screen Preference'),
        ),
        migrations.AddField(
            model_name='organism',
            name='reference',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Reference'),
        ),
        migrations.AddField(
            model_name='organism',
            name='res_property',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Resistance Property'),
        ),
        migrations.AddField(
            model_name='organism',
            name='strain_identification',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Strain Identification'),
        ),
        migrations.AddField(
            model_name='organism',
            name='strain_ids',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Strain IDs'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='biologist',
            field=models.ForeignKey(db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='lab_restriction',
            field=models.ForeignKey(blank=True, db_column='lab_restriction', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apputil.dictionary', verbose_name='Lab'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='mta_status',
            field=models.ForeignKey(blank=True, db_column='mta_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MTA+', to='apputil.dictionary', verbose_name='MTA Status'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='organism_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Organism ID'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='organism_name',
            field=models.ForeignKey(db_column='organism_name', on_delete=django.db.models.deletion.DO_NOTHING, related_name='OrganismName', to='dorganism.taxonomy', verbose_name='Organism Name'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='oxygen_pref',
            field=models.ForeignKey(blank=True, db_column='oxygen_pref', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Oxygen+', to='apputil.dictionary', verbose_name='Oxygen'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='pathogen_group',
            field=models.ForeignKey(blank=True, db_column='pathogen_group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Pathogen+', to='apputil.dictionary', verbose_name='Pathogen'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='risk_group',
            field=models.ForeignKey(blank=True, db_column='risk_group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Risk+', to='apputil.dictionary', verbose_name='Risk Group'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='strain_origin',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Origin of Strain'),
        ),
        migrations.AddIndex(
            model_name='organism',
            index=models.Index(fields=['strain_ids'], name='org_stid_idx'),
        ),
    ]
