# Generated by Django 3.2.6 on 2022-12-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0002_auto_20221207_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='urlname',
            field=models.SlugField(default=0, max_length=100, verbose_name='URLSpecie'),
            preserve_default=False,
        ),
    ]
