# Generated by Django 4.2.2 on 2023-11-05 05:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0003_alter_applicationlog_log_code_and_more'),
        ('dorganism', '0002_alter_organism_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism_batch',
            name='batch_quality',
            field=models.ForeignKey(blank=True, db_column='batch_quality', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_batchquality', to='apputil.dictionary', verbose_name='Quality'),
        ),
        migrations.AddField(
            model_name='organism_batch',
            name='quality_source',
            field=models.CharField(blank=True, max_length=150, verbose_name='QC Source'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='batch_id',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='Batch ID'),
        ),
    ]
