# Generated by Django 3.2.6 on 2022-12-07 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0003_auto_20221207_1106'),
        ('dorganism', '0003_taxonomy_urlname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism_batch',
            name='qc_record',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='QC Records'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='qc_status',
            field=models.ForeignKey(blank=True, db_column='qc_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_batch_QC+', to='apputil.dictionary', verbose_name='QC Notes'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='stock_date',
            field=models.DateField(blank=True, null=True, verbose_name='Stock Date'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='supplier',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='stock_type',
            field=models.ForeignKey(db_column='stock_type', default='none', on_delete=django.db.models.deletion.DO_NOTHING, related_name='orgbatch_stock_stock_type+', to='apputil.dictionary', verbose_name='Stock Type'),
            preserve_default=False,
        ),
    ]
