# Generated by Django 3.2.6 on 2022-11-28 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apputil', '0007_auto_20221128_1233'),
        ('dorganism', '0003_auto_20221123_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='acreated_at',
            field=models.DateTimeField(auto_now_add=True, default="2022-11-28 06:00:00.000000-09:00", verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism',
            name='acreated_by',
            field=models.ForeignKey(db_column='created_by', default='orgdb', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_created_by', to='apputil.applicationuser', verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism',
            name='adeleted_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='adeleted_by',
            field=models.ForeignKey(db_column='deleted_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='aupdated_by',
            field=models.ForeignKey(db_column='updated_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='biologist',
            field=models.ForeignKey(db_column='biologist', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='organism_name',
            field=models.ForeignKey(db_column='organism_name', on_delete=django.db.models.deletion.DO_NOTHING, to='dorganism.taxonomy', verbose_name='Organism Name'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='acreated_at',
            field=models.DateTimeField(auto_now_add=True, default="2022-11-28 06:00:00.000000-09:00" , verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='acreated_by',
            field=models.ForeignKey(db_column='created_by', default='orgdb', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_batch_created_by', to='apputil.applicationuser', verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='adeleted_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='adeleted_by',
            field=models.ForeignKey(db_column='deleted_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_batch_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='aupdated_by',
            field=models.ForeignKey(db_column='updated_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_batch_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='biologist',
            field=models.ForeignKey(db_column='biologist', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='organism_id',
            field=models.ForeignKey(db_column='organism_id-batch', on_delete=django.db.models.deletion.DO_NOTHING, to='dorganism.organism', verbose_name='Organism ID'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='acreated_at',
            field=models.DateTimeField(auto_now_add=True, default="2022-11-28 06:00:00.000000-09:00" , verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='acreated_by',
            field=models.ForeignKey(db_column='created_by', default='orgdb', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_culture_created_by', to='apputil.applicationuser', verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='adeleted_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='adeleted_by',
            field=models.ForeignKey(db_column='deleted_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_culture_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='aupdated_by',
            field=models.ForeignKey(db_column='updated_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_culture_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='biologist',
            field=models.ForeignKey(db_column='biologist', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='organism_id',
            field=models.ForeignKey(db_column='organism_id-culture', on_delete=django.db.models.deletion.DO_NOTHING, to='dorganism.organism', verbose_name='Organism ID'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='acreated_at',
            field=models.DateTimeField(auto_now_add=True, default="2022-11-28 06:00:00.000000-09:00" , verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='acreated_by',
            field=models.ForeignKey(db_column='created_by', default='orgdb', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orgbatch_stock_created_by', to='apputil.applicationuser', verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='adeleted_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='adeleted_by',
            field=models.ForeignKey(db_column='deleted_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orgbatch_stock_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='aupdated_by',
            field=models.ForeignKey(db_column='updated_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orgbatch_stock_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='biologist',
            field=models.ForeignKey(db_column='biologist', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='orgbatch_id',
            field=models.ForeignKey(db_column='orgbatch_id', on_delete=django.db.models.deletion.DO_NOTHING, to='dorganism.organism_batch', verbose_name='OrgBatch ID'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='acreated_at',
            field=models.DateTimeField(auto_now_add=True, default="2022-11-28 06:00:00.000000-09:00" , verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='acreated_by',
            field=models.ForeignKey(db_column='created_by', default='orgdb', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taxonomy_created_by', to='apputil.applicationuser', verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='adeleted_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='adeleted_by',
            field=models.ForeignKey(db_column='deleted_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taxonomy_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='aupdated_by',
            field=models.ForeignKey(db_column='updated_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taxonomy_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='division',
            field=models.ForeignKey(blank=True, db_column='division', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Division+', to='apputil.dictionary', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='org_class',
            field=models.ForeignKey(blank=True, db_column='org_class', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Class+', to='apputil.dictionary', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='other_names',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Names'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='parent_tax_id',
            field=models.IntegerField(null=True, verbose_name='NCBI Parent Tax ID'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='tax_id',
            field=models.IntegerField(null=True, verbose_name='NCBI Tax ID'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='tax_rank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Taxonomy Rank'),
        ),
    ]
