# Generated by Django 3.2.6 on 2022-12-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0004_auto_20221207_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organism',
            options={'ordering': ['organism_name']},
        ),
    ]
