# Generated by Django 4.1.3 on 2023-06-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0004_alter_organism_res_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='mta_notes',
            field=models.CharField(blank=True, max_length=150, verbose_name='MTA Notes'),
        ),
    ]
