# Generated by Django 4.1.3 on 2022-11-29 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0005_alter_organism_acreated_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organism',
            old_name='acreated_by',
            new_name='acreated',
        ),
        migrations.RenameField(
            model_name='organism_batch',
            old_name='acreated_by',
            new_name='acreated',
        ),
        migrations.RenameField(
            model_name='organism_culture',
            old_name='acreated_by',
            new_name='acreated',
        ),
        migrations.RenameField(
            model_name='orgbatch_stock',
            old_name='acreated_by',
            new_name='acreated',
        ),
        migrations.RenameField(
            model_name='taxonomy',
            old_name='acreated_by',
            new_name='acreated',
        ),
    ]
