# Generated by Django 4.1.5 on 2023-06-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0002_image_document_image_img_name_idx_image_img_scr_idx_and_more'),
        ('dorganism', '0005_organism_mta_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='assoc_documents',
            field=models.ManyToManyField(to='apputil.document'),
        ),
        migrations.AddField(
            model_name='organism',
            name='assoc_images',
            field=models.ManyToManyField(to='apputil.image'),
        ),
    ]
