# Generated by Django 3.2.6 on 2022-12-15 05:03

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0004_alter_dictionary_dict_desc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dorganism', '0005_alter_organism_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organism',
            options={},
        ),
        migrations.AddField(
            model_name='orgbatch_stock',
            name='stock_note',
            field=models.CharField(blank=True, max_length=10, verbose_name='Stock Note'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='biologist',
            field=models.ForeignKey(blank=True, db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_Biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='gen_property',
            field=models.CharField(blank=True, default='gne', max_length=350, verbose_name='Genetic Property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism',
            name='growth_preference',
            field=models.CharField(blank=True, default='1', max_length=250, verbose_name='Growth/Screen Preference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism',
            name='lab_restriction',
            field=models.ForeignKey(blank=True, db_column='lab_restriction', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organism_MTA+', to='apputil.dictionary', verbose_name='Lab'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='mta_document',
            field=models.CharField(blank=True, default='1', max_length=150, verbose_name='MTA Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism',
            name='reference',
            field=models.CharField(blank=True, default=1, max_length=150, verbose_name='Reference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism',
            name='res_property',
            field=models.CharField(blank=True, default=1, max_length=350, verbose_name='Resistance Property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism',
            name='sequence_link',
            field=models.CharField(blank=True, default=1, max_length=500, verbose_name='Sequence Link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism',
            name='strain_code',
            field=models.CharField(blank=True, default=1, max_length=30, verbose_name='Strain Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism',
            name='strain_identification',
            field=models.CharField(blank=True, default=1, max_length=150, verbose_name='Strain Identification'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism',
            name='strain_ids',
            field=models.CharField(blank=True, default=1, max_length=200, verbose_name='Strain IDs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism',
            name='strain_notes',
            field=models.CharField(blank=True, default=1, max_length=250, verbose_name='Strain Notes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism',
            name='strain_origin',
            field=models.CharField(blank=True, default=1, max_length=350, verbose_name='Origin of Strain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism',
            name='tax_id',
            field=models.IntegerField(default=0, verbose_name='NCBI Tax ID'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='batch_no',
            field=models.IntegerField(default=-1, verbose_name='Batch No'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='batch_notes',
            field=models.CharField(blank=True, default=1, max_length=500, verbose_name='Batch Notes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='qc_record',
            field=models.CharField(blank=True, default=1, max_length=150, verbose_name='QC Records'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='stock_level',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, editable=False, size=3, verbose_name='Stock Levels'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='supplier',
            field=models.CharField(blank=True, default=1, max_length=250, verbose_name='Supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='supplier_code',
            field=models.CharField(blank=True, default=1, max_length=120, verbose_name='Supplier Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='supplier_po',
            field=models.CharField(blank=True, default=1, max_length=120, verbose_name='Supplier PO'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='atmosphere',
            field=models.CharField(blank=True, default=1, max_length=120, verbose_name='Atmosphere'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='culture_type',
            field=models.CharField(blank=True, default=1, max_length=120, verbose_name='Culture Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='labware',
            field=models.CharField(blank=True, default=1, max_length=120, verbose_name='Labware'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='media',
            field=models.CharField(blank=True, default=1, max_length=120, verbose_name='Media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='media_use',
            field=models.CharField(blank=True, default=1, max_length=120, verbose_name='Media Use'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='notes',
            field=models.CharField(blank=True, default=1, max_length=512, verbose_name='Media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='temperature',
            field=models.CharField(blank=True, default=1, max_length=25, verbose_name='Temperature'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='location_column',
            field=models.CharField(blank=True, default=1, max_length=10, verbose_name='Column'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='location_freezer',
            field=models.CharField(blank=True, default=1, max_length=80, verbose_name='Freezer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='location_rack',
            field=models.CharField(blank=True, default=1, max_length=10, verbose_name='Rack'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='location_slot',
            field=models.CharField(blank=True, default=1, max_length=10, verbose_name='Slot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='orgbatch_id',
            field=models.ForeignKey(db_column='orgbatch_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='orgbatch_stock_orgbatch_id+', to='dorganism.organism_batch', verbose_name='OrgBatch ID'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='passage_no',
            field=models.IntegerField(blank=True, default=0, verbose_name='Passage No'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='stock_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Stock Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='code',
            field=models.CharField(blank=True, default=1, max_length=15, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='division',
            field=models.ForeignKey(db_column='division', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Division', to='apputil.dictionary', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='lineage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60), null=True, size=30),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='other_names',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='Other Names'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='parent_tax_id',
            field=models.IntegerField(default=0, verbose_name='NCBI Parent Tax ID'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='tax_id',
            field=models.IntegerField(default=0, verbose_name='NCBI Tax ID'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='tax_rank',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='Taxonomy Rank'),
            preserve_default=False,
        ),
    ]
