# Generated by Django 4.1.5 on 2023-06-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0006_organism_assoc_documents_organism_assoc_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organism',
            name='assoc_documents',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='assoc_images',
        ),
    ]
