# Generated by Django 4.1.1 on 2022-12-19 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apputil', '0005_alter_dictionary_acreated_alter_dictionary_adeleted_and_more'),
        ('dorganism', '0006_auto_20221215_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organism',
            options={'ordering': ['organism_name']},
        ),
        migrations.RemoveField(
            model_name='orgbatch_stock',
            name='passage_no',
        ),
        migrations.AddField(
            model_name='orgbatch_stock',
            name='passage_notes',
            field=models.CharField(blank=True, max_length=30, verbose_name='Passage Notes'),
        ),
        migrations.AddField(
            model_name='orgbatch_stock',
            name='stock_id',
            field=models.CharField(blank=True, max_length=15, verbose_name='Stock ID'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='acreated',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='adeleted',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='aupdated',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='biologist',
            field=models.ForeignKey(blank=True, db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_Biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='lab_restriction',
            field=models.ForeignKey(blank=True, db_column='lab_restriction', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_MTA+', to='apputil.dictionary', verbose_name='Lab'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='mta_status',
            field=models.ForeignKey(blank=True, db_column='mta_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_MTA+', to='apputil.dictionary', verbose_name='MTA Status'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='oxygen_pref',
            field=models.ForeignKey(blank=True, db_column='oxygen_pref', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_Oxygen+', to='apputil.dictionary', verbose_name='Oxygen'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='pathogen_group',
            field=models.ForeignKey(blank=True, db_column='pathogen_group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_Pathogen+', to='apputil.dictionary', verbose_name='Pathogen'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='risk_group',
            field=models.ForeignKey(blank=True, db_column='risk_group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_Risk+', to='apputil.dictionary', verbose_name='Risk Group'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='acreated',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='adeleted',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='aupdated',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='biologist',
            field=models.ForeignKey(db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_Biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='organism_id',
            field=models.ForeignKey(db_column='organism_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_organism_id+', to='dorganism.organism', verbose_name='Organism ID'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='qc_status',
            field=models.ForeignKey(blank=True, db_column='qc_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_QC+', to='apputil.dictionary', verbose_name='QC Notes'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='acreated',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='adeleted',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='aupdated',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='biologist',
            field=models.ForeignKey(db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_Biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='organism_id',
            field=models.ForeignKey(db_column='organism_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_organism_id+', to='dorganism.organism', verbose_name='Organism ID'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='acreated',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='adeleted',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='aupdated',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='biologist',
            field=models.ForeignKey(db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_Biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='orgbatch_id',
            field=models.ForeignKey(db_column='orgbatch_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_orgbatch_id+', to='dorganism.organism_batch', verbose_name='OrgBatch ID'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='stock_type',
            field=models.ForeignKey(db_column='stock_type', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_stock_type+', to='apputil.dictionary', verbose_name='Stock Type'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='acreated',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='adeleted',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='aupdated',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddIndex(
            model_name='orgbatch_stock',
            index=models.Index(fields=['stock_id'], name='orgbstock_stid_idx'),
        ),
    ]
