# Generated by Django 4.1.3 on 2022-11-29 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0007_alter_organism_adeleted_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organism',
            old_name='adeleted_by',
            new_name='adeleted',
        ),
        migrations.RenameField(
            model_name='organism',
            old_name='aupdated_by',
            new_name='aupdated',
        ),
        migrations.RenameField(
            model_name='organism_batch',
            old_name='adeleted_by',
            new_name='adeleted',
        ),
        migrations.RenameField(
            model_name='organism_batch',
            old_name='aupdated_by',
            new_name='aupdated',
        ),
        migrations.RenameField(
            model_name='organism_culture',
            old_name='adeleted_by',
            new_name='adeleted',
        ),
        migrations.RenameField(
            model_name='organism_culture',
            old_name='aupdated_by',
            new_name='aupdated',
        ),
        migrations.RenameField(
            model_name='orgbatch_stock',
            old_name='adeleted_by',
            new_name='adeleted',
        ),
        migrations.RenameField(
            model_name='orgbatch_stock',
            old_name='aupdated_by',
            new_name='aupdated',
        ),
        migrations.RenameField(
            model_name='taxonomy',
            old_name='adeleted_by',
            new_name='adeleted',
        ),
        migrations.RenameField(
            model_name='taxonomy',
            old_name='aupdated_by',
            new_name='aupdated',
        ),
    ]
