# Generated by Django 4.1.5 on 2023-06-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0002_image_document_image_img_name_idx_image_img_scr_idx_and_more'),
        ('dorganism', '0007_remove_organism_assoc_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='assoc_documents',
            field=models.ManyToManyField(db_table='org_doc', related_name='%(class)s_document', to='apputil.document', verbose_name='Douments'),
        ),
        migrations.AddField(
            model_name='organism',
            name='assoc_images',
            field=models.ManyToManyField(db_table='org_img', related_name='%(class)s_image', to='apputil.image', verbose_name='Images'),
        ),
    ]
