# Generated by Django 4.1.1 on 2023-01-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0007_alter_organism_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organism',
            options={'ordering': ['organism_id']},
        ),
    ]
