# Generated by Django 4.1.5 on 2023-03-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0008_alter_organism_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organism_batch',
            name='orgbatch_orgbatch_idx',
        ),
        migrations.RemoveField(
            model_name='organism_batch',
            name='batch_no',
        ),
        migrations.AddField(
            model_name='organism_batch',
            name='batch_id',
            field=models.CharField(default=0, max_length=5, verbose_name='Batch ID'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='organism_batch',
            index=models.Index(fields=['organism_id', 'batch_id'], name='orgbatch_orgbatch_idx'),
        ),
    ]
