# Generated by Django 4.1.5 on 2023-03-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0009_remove_organism_batch_orgbatch_orgbatch_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='n_left',
            field=models.IntegerField(default=0, editable=False, verbose_name='#Vials left'),
        ),
    ]
