# Generated by Django 4.2.1 on 2023-06-30 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dorganism', '0010_alter_orgbatch_stock_orgbatch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgBatch_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('image_name', models.CharField(max_length=120, unique=True, verbose_name='Name_imgbatch')),
                ('image_file', models.ImageField(upload_to='images/orgbatch', verbose_name='Image_batch')),
                ('image_type', models.CharField(max_length=25, verbose_name='Type')),
                ('image_desc', models.CharField(blank=True, default='Description', max_length=140, verbose_name='Description_imgbatch')),
                ('image_source', models.CharField(blank=True, default='source', max_length=50, verbose_name='Source_imgbatch')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('orgbatch_id', models.ForeignKey(db_column='orgbatch_id', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_orgbatch_id', to='dorganism.organism_batch', verbose_name='OrgBatch ID')),
            ],
            options={
                'db_table': 'orgbatch_image',
                'ordering': ['image_name'],
                'indexes': [models.Index(fields=['image_name'], name='orgbatch_img_name_idx'), models.Index(fields=['image_source'], name='orgbatch_img_scr_idx')],
            },
        ),
    ]
