# Generated by Django 4.1.5 on 2023-03-27 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0009_alter_applicationlog_options_dictionary_dict_sort_and_more'),
        ('dorganism', '0011_alter_orgbatch_stock_n_left'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organism_batch',
            name='orgbatch_supp_idx',
        ),
        migrations.RemoveIndex(
            model_name='orgbatch_stock',
            name='orgbstock_stid_idx',
        ),
        migrations.RemoveField(
            model_name='organism_batch',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='organism_batch',
            name='supplier_code',
        ),
        migrations.RemoveField(
            model_name='organism_batch',
            name='supplier_po',
        ),
        migrations.RemoveField(
            model_name='organism_culture',
            name='media_use',
        ),
        migrations.RemoveField(
            model_name='orgbatch_stock',
            name='stock_id',
        ),
        migrations.AddField(
            model_name='organism',
            name='source',
            field=models.CharField(blank=True, max_length=250, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='organism',
            name='source_code',
            field=models.CharField(blank=True, max_length=120, verbose_name='Source Code'),
        ),
        migrations.AddField(
            model_name='organism',
            name='supplier_po',
            field=models.CharField(blank=True, max_length=120, verbose_name='Purchase Order'),
        ),
        migrations.AddField(
            model_name='organism_culture',
            name='culture_source',
            field=models.ForeignKey(db_column='culture_source', default=None, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_culture_source+', to='apputil.dictionary', verbose_name='Source'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='culture_type',
            field=models.ForeignKey(db_column='culture_type', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_culture_type+', to='apputil.dictionary', verbose_name='Culture Type'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='notes',
            field=models.CharField(blank=True, max_length=512, verbose_name='Culture Notes'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='n_created',
            field=models.IntegerField(default=0, editable=False, verbose_name='#Vials created'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='orgbatch_id',
            field=models.ForeignKey(db_column='orgbatch_id', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_orgbatch_id+', to='dorganism.organism_batch', verbose_name='OrgBatch ID'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='stock_date',
            field=models.DateField(editable=False, verbose_name='Stock Date'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='stock_type',
            field=models.ForeignKey(db_column='stock_type', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_stock_type+', to='apputil.dictionary', verbose_name='Stock Type'),
        ),
        migrations.AddIndex(
            model_name='organism',
            index=models.Index(fields=['source'], name='org_source_idx'),
        ),
    ]
