# Generated by Django 4.1.5 on 2023-03-27 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0012_remove_organism_batch_orgbatch_supp_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organism_culture',
            old_name='media',
            new_name='media_use',
        ),
    ]
