# Generated by Django 4.2.1 on 2023-06-30 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0012_remove_orgbatch_image_orgbatch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgbatch_image',
            name='img_orgbatch_id',
            field=models.ForeignKey(db_column='img_orgbatch_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_img_orgbatch_id', to='dorganism.organism_batch', verbose_name='Img OrgBatch ID'),
        ),
    ]
