# Generated by Django 4.1.5 on 2023-04-11 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0009_alter_applicationlog_options_dictionary_dict_sort_and_more'),
        ('dorganism', '0012_remove_organism_batch_orgbatch_supp_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organism_culture',
            options={'ordering': ['organism_id', 'culture_type', 'media']},
        ),
        migrations.RemoveIndex(
            model_name='organism_culture',
            name='orgcult_media_idx',
        ),
        migrations.RenameField(
            model_name='organism_culture',
            old_name='notes',
            new_name='culture_notes',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='supplier_po',
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='culture_source',
            field=models.ForeignKey(db_column='culture_source', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_culture_source+', to='apputil.dictionary', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='culture_type',
            field=models.ForeignKey(db_column='culture_type', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_culture_type+', to='apputil.dictionary', verbose_name='Culture Type'),
        ),
        migrations.AddIndex(
            model_name='organism_culture',
            index=models.Index(fields=['media'], name='orgcult_media_idx'),
        ),
    ]
