# Generated by Django 4.1.5 on 2023-04-12 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0010_alter_applicationlog_log_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dorganism', '0013_alter_organism_culture_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='biologist',
            field=models.ForeignKey(blank=True, db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='lab_restriction',
            field=models.ForeignKey(blank=True, db_column='lab_restriction', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_lab', to='apputil.dictionary', verbose_name='Lab'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='mta_status',
            field=models.ForeignKey(blank=True, db_column='mta_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mta', to='apputil.dictionary', verbose_name='MTA Status'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='organism_name',
            field=models.ForeignKey(db_column='organism_name', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_organism_name', to='dorganism.taxonomy', verbose_name='Organism Name'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='oxygen_pref',
            field=models.ForeignKey(blank=True, db_column='oxygen_pref', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_oxygen', to='apputil.dictionary', verbose_name='Oxygen'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='pathogen_group',
            field=models.ForeignKey(blank=True, db_column='pathogen_group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_pathogen', to='apputil.dictionary', verbose_name='Pathogen'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='risk_group',
            field=models.ForeignKey(blank=True, db_column='risk_group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_risk', to='apputil.dictionary', verbose_name='Risk Group'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='biologist',
            field=models.ForeignKey(db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='organism_id',
            field=models.ForeignKey(db_column='organism_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_organism_id', to='dorganism.organism', verbose_name='Organism ID'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='qc_status',
            field=models.ForeignKey(blank=True, db_column='qc_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_qc', to='apputil.dictionary', verbose_name='QC Notes'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='biologist',
            field=models.ForeignKey(db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='culture_source',
            field=models.ForeignKey(db_column='culture_source', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_culture_source', to='apputil.dictionary', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='culture_type',
            field=models.ForeignKey(db_column='culture_type', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_culture_type', to='apputil.dictionary', verbose_name='Culture Type'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='organism_id',
            field=models.ForeignKey(db_column='organism_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_organism_id', to='dorganism.organism', verbose_name='Organism ID'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='biologist',
            field=models.ForeignKey(db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='orgbatch_id',
            field=models.ForeignKey(db_column='orgbatch_id', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_organism_id', to='dorganism.organism_batch', verbose_name='OrgBatch ID'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='stock_type',
            field=models.ForeignKey(db_column='stock_type', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_stock', to='apputil.dictionary', verbose_name='Stock Type'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='division',
            field=models.ForeignKey(db_column='division', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_division', to='apputil.dictionary', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='org_class',
            field=models.ForeignKey(blank=True, db_column='org_class', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_class', to='apputil.dictionary', verbose_name='Class'),
        ),
    ]
