# Generated by Django 4.1.5 on 2023-04-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0014_alter_organism_biologist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism_batch',
            name='batch_id',
            field=models.CharField(blank=True, max_length=5, verbose_name='Batch ID'),
        ),
    ]
