# Generated by Django 4.2.1 on 2023-06-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0014_rename_image_file_orgbatch_image_image_file_orgbatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgbatch_image',
            options={'ordering': ['image_name_orgbatch']},
        ),
        migrations.RemoveIndex(
            model_name='orgbatch_image',
            name='orgbatch_img_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='orgbatch_image',
            name='orgbatch_img_scr_idx',
        ),
        migrations.RenameField(
            model_name='orgbatch_image',
            old_name='image_desc',
            new_name='image_desc_orgbatch',
        ),
        migrations.RenameField(
            model_name='orgbatch_image',
            old_name='image_name',
            new_name='image_name_orgbatch',
        ),
        migrations.RenameField(
            model_name='orgbatch_image',
            old_name='image_source',
            new_name='image_source_orgbatch',
        ),
        migrations.RenameField(
            model_name='orgbatch_image',
            old_name='image_type',
            new_name='image_type_orgbatch',
        ),
        migrations.AddIndex(
            model_name='orgbatch_image',
            index=models.Index(fields=['image_name_orgbatch'], name='orgbatch_img_name_idx'),
        ),
        migrations.AddIndex(
            model_name='orgbatch_image',
            index=models.Index(fields=['image_source_orgbatch'], name='orgbatch_img_scr_idx'),
        ),
    ]
