# Generated by Django 4.2.1 on 2023-07-06 12:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0015_alter_orgbatch_image_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgbatch_image',
            options={'ordering': ['orgbatch_id', 'image_name']},
        ),
        migrations.RemoveIndex(
            model_name='orgbatch_image',
            name='orgbatch_img_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='orgbatch_image',
            name='orgbatch_img_scr_idx',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='assoc_images',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='collect_age',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='collect_body',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='collect_city',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='collect_gender',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='collect_institution',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='collect_notes',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='growth_preference',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='prep_notes',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='received_as',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='received_date',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='sequence_link',
        ),
        migrations.RemoveField(
            model_name='organism_culture',
            name='labware',
        ),
        migrations.RemoveField(
            model_name='orgbatch_image',
            name='image_desc_orgbatch',
        ),
        migrations.RemoveField(
            model_name='orgbatch_image',
            name='image_file_orgbatch',
        ),
        migrations.RemoveField(
            model_name='orgbatch_image',
            name='image_name_orgbatch',
        ),
        migrations.RemoveField(
            model_name='orgbatch_image',
            name='image_source_orgbatch',
        ),
        migrations.RemoveField(
            model_name='orgbatch_image',
            name='image_type_orgbatch',
        ),
        migrations.RemoveField(
            model_name='orgbatch_image',
            name='img_orgbatch_id',
        ),
        migrations.RemoveField(
            model_name='orgbatch_stock',
            name='passage_notes',
        ),
        migrations.AddField(
            model_name='organism',
            name='collect_region',
            field=models.CharField(blank=True, max_length=25, verbose_name='Region/City'),
        ),
        migrations.AddField(
            model_name='organism',
            name='collect_site',
            field=models.CharField(blank=True, max_length=25, verbose_name='Site/Org'),
        ),
        migrations.AddField(
            model_name='organism',
            name='collect_tissue',
            field=models.CharField(blank=True, max_length=20, verbose_name='From Tissue/Organ'),
        ),
        migrations.AddField(
            model_name='organism',
            name='patient',
            field=models.CharField(blank=True, max_length=20, verbose_name='Patient Info'),
        ),
        migrations.AddField(
            model_name='organism',
            name='patient_diagnosis',
            field=models.CharField(blank=True, max_length=20, verbose_name='Patient Diagnosis'),
        ),
        migrations.AddField(
            model_name='organism',
            name='sero_clone',
            field=models.CharField(blank=True, max_length=50, verbose_name='MLST/Serotype'),
        ),
        migrations.AddField(
            model_name='organism_culture',
            name='addition',
            field=models.CharField(blank=True, max_length=25, verbose_name='Addition'),
        ),
        migrations.AddField(
            model_name='orgbatch_image',
            name='image_desc',
            field=models.CharField(blank=True, max_length=140, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='orgbatch_image',
            name='image_file',
            field=models.ImageField(default=1, upload_to='images/orgbatch', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgbatch_image',
            name='image_name',
            field=models.CharField(default=1, max_length=120, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgbatch_image',
            name='image_source',
            field=models.CharField(blank=True, max_length=50, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='orgbatch_image',
            name='image_type',
            field=models.CharField(default=1, max_length=25, verbose_name='Image Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgbatch_image',
            name='orgbatch_id',
            field=models.ForeignKey(db_column='orgbatch_id', default=1, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_orgbatch_id', to='dorganism.organism_batch', verbose_name='OrgBatch ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism',
            name='collect_date',
            field=models.DateField(blank=True, null=True, verbose_name='Collection Date'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='collect_specie',
            field=models.CharField(blank=True, max_length=20, verbose_name='From Specie/Location'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='gen_property',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Genotype'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='res_property',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Phenotype'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='batch_id',
            field=models.CharField(blank=True, max_length=12, verbose_name='Batch ID'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='orgbatch_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='OrgBatch ID'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='stock_level',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Stock Levels'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='culture_notes',
            field=models.CharField(blank=True, max_length=512, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='lineage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60), null=True, size=30, verbose_name='Lineage'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='organism_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='urlname',
            field=models.SlugField(max_length=100, verbose_name='URLName'),
        ),
        migrations.AddIndex(
            model_name='orgbatch_image',
            index=models.Index(fields=['image_name'], name='obimg_name_idx'),
        ),
        migrations.AddIndex(
            model_name='orgbatch_image',
            index=models.Index(fields=['image_source'], name='obimg_scr_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomy',
            index=models.Index(fields=['tax_rank'], name='tax_rnk_idx'),
        ),
    ]
