# Generated by Django 4.1.5 on 2023-04-18 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0016_alter_orgbatch_stock_orgbatch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='collect_age',
            field=models.CharField(blank=True, max_length=10, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='organism',
            name='collect_body',
            field=models.CharField(blank=True, max_length=20, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='organism',
            name='collect_city',
            field=models.CharField(blank=True, max_length=25, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='organism',
            name='collect_country',
            field=models.CharField(blank=True, max_length=25, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='organism',
            name='collect_date',
            field=models.DateField(blank=True, null=True, verbose_name='Collection'),
        ),
        migrations.AddField(
            model_name='organism',
            name='collect_gender',
            field=models.CharField(blank=True, max_length=5, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='organism',
            name='collect_institution',
            field=models.CharField(blank=True, max_length=25, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='organism',
            name='collect_notes',
            field=models.CharField(blank=True, max_length=120, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='organism',
            name='collect_specie',
            field=models.CharField(blank=True, max_length=20, verbose_name='From'),
        ),
        migrations.AddField(
            model_name='organism',
            name='prep_notes',
            field=models.CharField(blank=True, max_length=250, verbose_name='Preparation Notes'),
        ),
        migrations.AddField(
            model_name='organism',
            name='received_as',
            field=models.CharField(blank=True, max_length=120, verbose_name='Recieved as'),
        ),
        migrations.AddField(
            model_name='organism',
            name='received_date',
            field=models.DateField(blank=True, null=True, verbose_name='Recieved'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='orgbatch_id',
            field=models.ForeignKey(db_column='orgbatch_id', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_organism_id', to='dorganism.organism_batch', verbose_name='OrgBatch ID'),
        ),
    ]
