# Generated by Django 4.2.1 on 2023-07-07 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0006_remove_image_acreated_remove_image_adeleted_and_more'),
        ('dorganism', '0016_alter_orgbatch_image_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism_batch',
            name='qc_status',
            field=models.ForeignKey(blank=True, db_column='qc_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_qc', to='apputil.dictionary', verbose_name='QC status'),
        ),
        migrations.AlterField(
            model_name='orgbatch_image',
            name='orgbatch_id',
            field=models.ForeignKey(db_column='orgbatch_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_orgbatch_id', to='dorganism.organism_batch', verbose_name='OrgBatch ID'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='n_created',
            field=models.IntegerField(default=0, verbose_name='#Vials created'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='orgbatch_id',
            field=models.ForeignKey(db_column='orgbatch_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_orgbatch_id', to='dorganism.organism_batch', verbose_name='OrgBatch ID'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='stock_date',
            field=models.DateField(verbose_name='Stock Date'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='stock_type',
            field=models.ForeignKey(db_column='stock_type', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_stock', to='apputil.dictionary', verbose_name='Stock Type'),
        ),
    ]
