# Generated by Django 4.2.1 on 2023-07-10 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dorganism', '0018_alter_organism_collect_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism_batch',
            name='biologist',
            field=models.ForeignKey(blank=True, db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='organism_batch',
            name='stock_level',
            field=models.CharField(blank=True, max_length=20, verbose_name='Stock Levels'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='addition',
            field=models.CharField(blank=True, max_length=55, verbose_name='Addition'),
        ),
        migrations.AlterField(
            model_name='organism_culture',
            name='biologist',
            field=models.ForeignKey(blank=True, db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='biologist',
            field=models.ForeignKey(blank=True, db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist'),
        ),
        migrations.AlterField(
            model_name='orgbatch_stock',
            name='stock_date',
            field=models.DateField(blank=True, null=True, verbose_name='Stock Date'),
        ),
    ]
