# Generated by Django 4.1.1 on 2022-10-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxo',
            fields=[
                ('Name', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='Specietest')),
                ('Class_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='classtest', to='app.dictionaries', verbose_name='Class')),
            ],
        ),
    ]
