# Generated by Django 3.2.6 on 2022-11-16 05:07

from django.db import migrations, models
import django_rdkit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dTestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('drug_id', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('drug_name', models.CharField(blank=True, max_length=50, null=True)),
                ('drug_code', models.CharField(blank=True, max_length=10, null=True)),
                ('drug_synonyms', models.CharField(blank=True, max_length=1024, null=True)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('cas', models.CharField(blank=True, max_length=15, null=True)),
                ('unii', models.CharField(blank=True, max_length=15, null=True)),
                ('access_ids', models.CharField(blank=True, max_length=250, null=True)),
                ('db_access_ids', models.TextField(blank=True, null=True)),
                ('drug_mol', django_rdkit.models.fields.MolField(blank=True, null=True)),
                ('drug_smiles', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'drugbank',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Taxo',
        ),
    ]
