# Generated by Django 6.0.1 on 2026-02-10 04:46

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apputil', '0005_alter_applicationuser_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peptide',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('peptide_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Peptide ID')),
                ('peptide_name', models.CharField(blank=True, max_length=200, verbose_name='Peptide Name')),
                ('peptide_notes', models.CharField(blank=True, max_length=1024, verbose_name='Peptide Notes')),
                ('peptide_panel', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=20, verbose_name='Panel')),
                ('peptide_origin', models.CharField(blank=True, max_length=512, verbose_name='Origin of Peptide')),
                ('bilm', models.CharField(blank=True, max_length=200, verbose_name='BILM')),
                ('helm', models.CharField(blank=True, max_length=200, verbose_name='HELM')),
                ('seq', models.CharField(blank=True, max_length=200, verbose_name='Seq')),
                ('reference', models.CharField(blank=True, max_length=150, verbose_name='Reference')),
                ('mta_notes', models.CharField(blank=True, max_length=512, verbose_name='MTA Notes')),
                ('mta_document', models.CharField(blank=True, max_length=150, verbose_name='MTA Document')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('assoc_documents', models.ManyToManyField(blank=True, db_table='peptide_doc', related_name='%(class)s_document', to='apputil.document', verbose_name='Documents')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('biologist', models.ForeignKey(blank=True, db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist')),
                ('mta_status', models.ForeignKey(blank=True, db_column='mta_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mta', to='apputil.dictionary', verbose_name='MTA Status')),
                ('peptide_type', models.ForeignKey(blank=True, db_column='peptide_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_peptide_type', to='apputil.dictionary', verbose_name='Peptide Type')),
            ],
            options={
                'db_table': 'peptide',
            },
        ),
        migrations.CreateModel(
            name='Peptide_Batch',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('pepbatch_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='PepBatch ID')),
                ('batch_id', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='Batch ID')),
                ('batch_notes', models.CharField(blank=True, max_length=500, verbose_name='Batch Notes')),
                ('source', models.CharField(blank=True, max_length=250, verbose_name='Source')),
                ('source_code', models.CharField(blank=True, max_length=120, verbose_name='Source Code')),
                ('peptide_tags', models.CharField(blank=True, max_length=80, verbose_name='Tags')),
                ('quality_source', models.CharField(blank=True, max_length=150, verbose_name='QC Source')),
                ('qc_record', models.CharField(blank=True, max_length=150, verbose_name='QC Records')),
                ('stock_date', models.DateField(blank=True, null=True, verbose_name='Stock Date')),
                ('stock_level', models.CharField(blank=True, max_length=20, verbose_name='Stock Levels')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('biologist', models.ForeignKey(blank=True, db_column='biologist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_biologist', to=settings.AUTH_USER_MODEL, verbose_name='Biologist')),
                ('peptide_id', models.ForeignKey(db_column='peptide_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_peptide_id', to='dpeptide.peptide', verbose_name='Peptide ID')),
                ('qc_status', models.ForeignKey(blank=True, db_column='qc_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_qc', to='apputil.dictionary', verbose_name='QC status')),
                ('source_type', models.ForeignKey(blank=True, db_column='source_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_source_type', to='apputil.dictionary', verbose_name='Source Type')),
            ],
            options={
                'db_table': 'pepbatch',
                'ordering': ['pepbatch_id'],
            },
        ),
        migrations.AddIndex(
            model_name='peptide',
            index=models.Index(fields=['bilm'], name='pep_bilm_idx'),
        ),
        migrations.AddIndex(
            model_name='peptide',
            index=models.Index(fields=['peptide_type'], name='pep_type_idx'),
        ),
        migrations.AddIndex(
            model_name='peptide',
            index=models.Index(fields=['peptide_panel'], name='pep_panel_idx'),
        ),
        migrations.AddIndex(
            model_name='peptide_batch',
            index=models.Index(fields=['peptide_id', 'batch_id'], name='pepbatch_pepbatch_idx'),
        ),
        migrations.AddIndex(
            model_name='peptide_batch',
            index=models.Index(fields=['qc_status'], name='pepbatch_qc_idx'),
        ),
        migrations.AddIndex(
            model_name='peptide_batch',
            index=models.Index(fields=['stock_date'], name='pepbatch_sdate_idx'),
        ),
        migrations.AddIndex(
            model_name='peptide_batch',
            index=models.Index(fields=['stock_level'], name='pepbatch_slevel_idx'),
        ),
    ]
