# Generated by Django 4.1.3 on 2023-06-02 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('image_name', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True, verbose_name='Name')),
                ('image_file', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('image_type', models.CharField(max_length=10, verbose_name='Type')),
                ('image_desc', models.CharField(blank=True, max_length=140, verbose_name='Description')),
                ('image_source', models.CharField(blank=True, max_length=50, verbose_name='Source')),
                ('image_object', models.CharField(max_length=30, verbose_name='Object')),
                ('image_objectid', models.CharField(max_length=30, verbose_name='Object ID')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'app_image',
                'ordering': ['image_object', 'image_name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('doc_name', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True, verbose_name='Name')),
                ('doc_file', models.ImageField(upload_to='documents/', verbose_name='Document')),
                ('doc_type', models.CharField(max_length=10, verbose_name='Type')),
                ('doc_desc', models.CharField(blank=True, max_length=140, verbose_name='Description')),
                ('doc_source', models.CharField(blank=True, max_length=50, verbose_name='Source')),
                ('doc_object', models.CharField(max_length=30, verbose_name='Object')),
                ('doc_objectid', models.CharField(max_length=30, verbose_name='Object ID')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'app_document',
                'ordering': ['doc_object', 'doc_name'],
            },
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['image_object'], name='img_obj_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['image_objectid'], name='img_objid_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['image_source'], name='img_scr_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_object'], name='doc_obj_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_objectid'], name='doc_objid_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_source'], name='doc_scr_idx'),
        ),
    ]
