# Generated by Django 4.2.1 on 2023-06-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0002_image_document_image_img_name_idx_image_img_scr_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_file',
            field=models.FileField(upload_to='documents/', verbose_name='Document'),
        ),
    ]
