# Generated by Django 3.2.6 on 2022-11-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0002_alter_applicationuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationuser',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='permissions',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterModelTable(
            name='applicationlog',
            table='app_Log',
        ),
        migrations.AlterModelTable(
            name='applicationuser',
            table='app_user',
        ),
    ]
