# Generated by Django 3.2.6 on 2022-11-30 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0002_alter_dictionary_dict_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationlog',
            name='log_code',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_desc',
            field=models.CharField(blank=True, editable=False, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_object',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_proc',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_status',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_type',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_user',
            field=models.ForeignKey(db_column='log_user', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='username',
            field=models.CharField(max_length=55, unique=True, verbose_name='uquser'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='acreated',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dictionary_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='adeleted',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dictionary_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='aupdated',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dictionary_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
    ]
