# Generated by Django 4.2.2 on 2023-11-05 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0002_alter_applicationuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationlog',
            name='log_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=15, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_desc',
            field=models.CharField(blank=True, editable=False, max_length=1024, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_object',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=150, verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_proc',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, verbose_name='Procedure'),
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_status',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_type',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=15, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_user',
            field=models.ForeignKey(blank=True, db_column='log_user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
