# Generated by Django 3.2.6 on 2022-11-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0003_auto_20221122_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='permissions',
            field=models.IntegerField(default=0),
        ),
    ]
