# Generated by Django 3.2.6 on 2022-12-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0003_auto_20221207_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='dict_desc',
            field=models.CharField(blank=True, default=1, max_length=120, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
