# Generated by Django 4.2.13 on 2024-06-26 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0003_alter_applicationlog_log_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationuser',
            options={'ordering': ['name']},
        ),
    ]
