# Generated by Django 3.2.6 on 2022-12-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0003_auto_20221130_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='appuser name'),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='username',
            field=models.CharField(max_length=55, unique=True, verbose_name='user_identity_ldap'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='dict_desc',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Description'),
        ),
        migrations.AlterModelTable(
            name='dictionary',
            table='app_dictionary',
        ),
    ]
