# Generated by Django 3.2.6 on 2022-11-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0004_alter_applicationuser_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationuser',
            name='permissions',
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='permission',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
