# Generated by Django 4.1.3 on 2022-11-29 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0004_alter_dictionary_acreated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='acreated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
