# Generated by Django 4.2.2 on 2023-06-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0004_alter_document_doc_type_alter_image_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_desc',
            field=models.CharField(blank=True, default='description', max_length=140, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_source',
            field=models.CharField(blank=True, default='source', max_length=50, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_desc',
            field=models.CharField(blank=True, default='Description', max_length=140, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_source',
            field=models.CharField(blank=True, default='source', max_length=50, verbose_name='Source'),
        ),
    ]
