# Generated by Django 4.1.3 on 2022-11-29 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0005_alter_dictionary_acreated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='acreated_by',
            new_name='acreated',
        ),
    ]
