# Generated by Django 4.1.5 on 2023-01-06 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0005_alter_dictionary_acreated_alter_dictionary_adeleted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditModel',
        ),
    ]
