# Generated by Django 3.2.6 on 2022-11-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0005_auto_20221123_0426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'ordering': ['dict_value']},
        ),
        migrations.RenameField(
            model_name='dictionary',
            old_name='Dict_Desc',
            new_name='dict_desc',
        ),
        migrations.RenameField(
            model_name='dictionary',
            old_name='Dict_Value',
            new_name='dict_value',
        ),
        migrations.RenameField(
            model_name='dictionary',
            old_name='Dictionary_Class',
            new_name='dict_class',
        ),
        # migrations.RemoveField(
        #     model_name='dictionary',
        #     name='Dictionary_Class',
        # ),
        # migrations.AddField(
        #     model_name='dictionary',
        #     name='dict_class',
        #     field=models.CharField(default=1, max_length=30, verbose_name='Class'),
        #     preserve_default=False,
        # ),
        migrations.AddIndex(
            model_name='dictionary',
            index=models.Index(fields=['dict_class'], name='dict_class_idx'),
        ),
    ]
