# Generated by Django 3.2.6 on 2022-11-28 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0006_auto_20221123_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationlog',
            name='log_user',
            field=models.ForeignKey(db_column='log_user', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='acreated_at',
            field=models.DateTimeField(auto_now_add=True, default="2022-11-28 06:00:00.000000-09:00" , verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='acreated_by',
            field=models.ForeignKey(db_column='created_by', default='orgdb', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dictionary_created_by', to='apputil.applicationuser', verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='adeleted_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='adeleted_by',
            field=models.ForeignKey(db_column='deleted_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dictionary_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='aupdated_by',
            field=models.ForeignKey(db_column='updated_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dictionary_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='dict_class',
            field=models.CharField(max_length=30, verbose_name='Class'),
        ),
    ]
