# Generated by Django 4.1.1 on 2023-01-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0006_delete_auditmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'ordering': ['dict_class', 'dict_value']},
        ),
    ]
