# Generated by Django 4.1.3 on 2022-11-29 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0007_alter_dictionary_adeleted_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='adeleted_by',
            new_name='adeleted',
        ),
        migrations.RenameField(
            model_name='dictionary',
            old_name='aupdated_by',
            new_name='aupdated',
        ),
    ]
