# Generated by Django 4.1.5 on 2023-03-06 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0007_alter_dictionary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationuser',
            options={'ordering': ['username']},
        ),
    ]
