# Generated by Django 4.1.5 on 2023-03-20 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0008_alter_applicationuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationlog',
            options={'ordering': ['log_time', 'log_type']},
        ),
        migrations.AddField(
            model_name='dictionary',
            name='dict_sort',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_code',
            field=models.CharField(blank=True, db_index=True, default=0, editable=False, max_length=15, verbose_name='Log Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_desc',
            field=models.CharField(blank=True, default=0, editable=False, max_length=1024, verbose_name='Log Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_object',
            field=models.CharField(blank=True, db_index=True, default=0, editable=False, max_length=15, verbose_name='Log Object'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_proc',
            field=models.CharField(blank=True, db_index=True, default=0, editable=False, max_length=50, verbose_name='Log Procedure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_status',
            field=models.CharField(blank=True, db_index=True, default=0, editable=False, max_length=15, verbose_name='Log Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Log Time'),
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_type',
            field=models.CharField(blank=True, db_index=True, default=0, editable=False, max_length=15, verbose_name='Log Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='log_user',
            field=models.ForeignKey(blank=True, db_column='log_user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_User', to=settings.AUTH_USER_MODEL, verbose_name='Log User'),
        ),
        migrations.AddIndex(
            model_name='applicationlog',
            index=models.Index(fields=['log_code'], name='log_code_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationlog',
            index=models.Index(fields=['log_proc'], name='log_proc_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationlog',
            index=models.Index(fields=['log_type'], name='log_type_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationlog',
            index=models.Index(fields=['log_object'], name='log_object_idx'),
        ),
    ]
