# Generated by Django 4.1.5 on 2023-04-12 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0009_alter_applicationlog_options_dictionary_dict_sort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationlog',
            name='log_user',
            field=models.ForeignKey(blank=True, db_column='log_user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='Log User'),
        ),
    ]
