# Generated by Django 3.2.6 on 2022-12-05 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_rdkit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dorganism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('Drug_ID', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Drug ID')),
                ('Drug_Name', models.CharField(max_length=50, unique=True, verbose_name='Drug Name')),
                ('Drug_OtherName', models.CharField(blank=True, max_length=150, null=True, verbose_name='Drug OtherName')),
                ('Drug_Code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Drug Code')),
                ('Drug_Type', models.CharField(blank=True, max_length=15, null=True, verbose_name='Drug Type')),
                ('Drug_Note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Drug Notes')),
                ('ATC_CODE', models.CharField(blank=True, max_length=50, null=True, verbose_name='ATC Code')),
                ('Drug_Target', models.CharField(blank=True, max_length=50, null=True, verbose_name='Target')),
                ('Drug_SubTarget', models.CharField(blank=True, max_length=50, null=True, verbose_name='SubTraget')),
                ('Drug_Class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Class')),
                ('Drug_SubClass', models.CharField(blank=True, max_length=50, null=True, verbose_name='SubClass')),
                ('Mode_Action', models.CharField(blank=True, max_length=50, null=True, verbose_name='MoA')),
                ('Antimicro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Antimicro')),
                ('Antimicro_Type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Antimicro Type')),
                ('Max_Phase', models.CharField(blank=True, max_length=2, null=True, verbose_name='max Approval')),
                ('Approval_Note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Approval Notes')),
                ('Admin_Route', models.CharField(blank=True, max_length=50, null=True, verbose_name='Administration')),
                ('Application', models.CharField(blank=True, max_length=50, null=True, verbose_name='Application')),
                ('N_Compounds', models.IntegerField(blank=True, null=True, verbose_name='#Cmpds')),
                ('ChEMBL', models.CharField(blank=True, max_length=15, null=True, verbose_name='ChEMBL')),
                ('DrugBank', models.CharField(blank=True, max_length=15, null=True, verbose_name='DrugBank')),
                ('CAS', models.CharField(blank=True, max_length=15, null=True, verbose_name='CAS')),
                ('PubChem', models.CharField(blank=True, max_length=15, null=True, verbose_name='PubChem')),
                ('ChemSpider', models.CharField(blank=True, max_length=15, null=True, verbose_name='ChemSpider')),
                ('UNII', models.CharField(blank=True, max_length=15, null=True, verbose_name='UNII')),
                ('KEGG', models.CharField(blank=True, max_length=15, null=True, verbose_name='KEGG')),
                ('CompTox', models.CharField(blank=True, max_length=15, null=True, verbose_name='CompTox')),
                ('ECHA', models.CharField(blank=True, max_length=15, null=True, verbose_name='ECHA')),
                ('ChEBI', models.CharField(blank=True, max_length=15, null=True, verbose_name='ChEBI')),
                ('UQ_IMB', models.CharField(blank=True, max_length=15, null=True, verbose_name='IMB')),
                ('Vendor', models.CharField(blank=True, max_length=15, null=True, verbose_name='Vendor')),
                ('Vendor_CatNo', models.CharField(blank=True, max_length=15, null=True, verbose_name='CatNo')),
                ('Salt_Form', models.CharField(blank=True, max_length=15, null=True, verbose_name='SaltForm')),
                ('MW', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='MW')),
                ('MW_Full', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='MW Full')),
                ('MF', models.CharField(blank=True, max_length=15, null=True, verbose_name='MF')),
                ('MF_Full', models.CharField(blank=True, max_length=15, null=True, verbose_name='MF Full')),
                ('SMILES', models.CharField(blank=True, max_length=2048, null=True, verbose_name='SMILES')),
                ('smol', django_rdkit.models.fields.MolField(blank=True, null=True, verbose_name='MOL')),
                ('ffp2', django_rdkit.models.fields.BfpField(null=True)),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'drug',
            },
        ),
        migrations.CreateModel(
            name='VITEK_Card',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('Card_Barcode', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Card Barcode')),
                ('Card_Type', models.CharField(max_length=5, verbose_name='Card Type')),
                ('Card_Code', models.CharField(max_length=15, verbose_name='Card Code')),
                ('Expiry_Date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('Instrument', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Vitek SN')),
                ('Proc_Date', models.DateField(verbose_name='Processing Date')),
                ('Analysis_Time', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Analysis Time')),
                ('OrgBatch_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dorganism.organism_batch', verbose_name='OrgBatch ID')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitek_card_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitek_card_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitek_card_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'vitek_card',
                'ordering': ['Card_Type', 'Card_Code', 'Card_Barcode'],
            },
        ),
        migrations.CreateModel(
            name='VITEK_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('Process', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Vitek Process')),
                ('ID_Organism', models.CharField(blank=True, max_length=120, null=True, verbose_name='ID Organism')),
                ('ID_Probability', models.CharField(blank=True, max_length=120, null=True, verbose_name='ID Organism')),
                ('ID_Confidence', models.CharField(blank=True, max_length=120, null=True, verbose_name='ID Organism')),
                ('Filename', models.CharField(blank=True, max_length=120, null=True, verbose_name='PDF Filename')),
                ('Page_No', models.IntegerField(blank=True, null=True, verbose_name='PDF PageNo')),
                ('Card_Barcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ddrug.vitek_card', verbose_name='Card Barcode')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitek_id_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitek_id_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitek_id_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'vitek_id',
            },
        ),
        migrations.CreateModel(
            name='VITEK_AST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('Process', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Vitek Process')),
                ('MIC', models.CharField(blank=True, max_length=50, null=True, verbose_name='MIC')),
                ('BP_Profile', models.CharField(blank=True, max_length=5, null=True, verbose_name='Break Point')),
                ('BP_Comment', models.CharField(blank=True, max_length=120, null=True, verbose_name='Comment')),
                ('Selection', models.CharField(blank=True, max_length=20, null=True, verbose_name='Selection')),
                ('Organism', models.CharField(blank=True, max_length=120, null=True, verbose_name='Organism')),
                ('Filename', models.CharField(blank=True, max_length=120, null=True, verbose_name='PDF Filename')),
                ('Page_No', models.IntegerField(blank=True, null=True, verbose_name='PDF PageNo')),
                ('Card_Barcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ddrug.vitek_card', verbose_name='Card Barcode')),
                ('Drug_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ddrug.drug', verbose_name='Drug ID')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitek_ast_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitek_ast_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitek_ast_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'vitek_ast',
            },
        ),
        migrations.AddIndex(
            model_name='vitek_id',
            index=models.Index(fields=['ID_Organism'], name='vid_idorg_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_id',
            index=models.Index(fields=['ID_Probability'], name='vid_idprob_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_id',
            index=models.Index(fields=['ID_Confidence'], name='vid_idconf_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_id',
            index=models.Index(fields=['Filename'], name='vid_fname_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_card',
            index=models.Index(fields=['Card_Type'], name='vcard_ctype_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_card',
            index=models.Index(fields=['Card_Code'], name='vcard_ccode_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_card',
            index=models.Index(fields=['Card_Barcode'], name='vcard_bcode_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_card',
            index=models.Index(fields=['OrgBatch_ID'], name='vcard_orgbatch_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_ast',
            index=models.Index(fields=['Drug_ID'], name='vast_drugid_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_ast',
            index=models.Index(fields=['MIC'], name='vast_mic_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_ast',
            index=models.Index(fields=['BP_Profile'], name='vast_bprofile_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_ast',
            index=models.Index(fields=['Organism'], name='vast_org_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_ast',
            index=models.Index(fields=['Filename'], name='vast_fname_idx'),
        ),
    ]
