# Generated by Django 3.2.6 on 2022-11-28 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ddrug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='acreated_at',
            field=models.DateTimeField(auto_now_add=True, default="2022-11-28 06:00:00.000000-09:00" , verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drug',
            name='acreated_by',
            field=models.ForeignKey(db_column='created_by', default='orgdb', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_created_by', to='apputil.applicationuser', verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drug',
            name='adeleted_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='adeleted_by',
            field=models.ForeignKey(db_column='deleted_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='aupdated_by',
            field=models.ForeignKey(db_column='updated_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='vitek_ast',
            name='acreated_at',
            field=models.DateTimeField(auto_now_add=True, default="2022-11-28 06:00:00.000000-09:00" , verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitek_ast',
            name='acreated_by',
            field=models.ForeignKey(db_column='created_by', default='orgdb', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitek_ast_created_by', to='apputil.applicationuser', verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitek_ast',
            name='adeleted_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='vitek_ast',
            name='adeleted_by',
            field=models.ForeignKey(db_column='deleted_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitek_ast_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='vitek_ast',
            name='aupdated_by',
            field=models.ForeignKey(db_column='updated_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitek_ast_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='vitek_card',
            name='acreated_at',
            field=models.DateTimeField(auto_now_add=True, default="2022-11-28 06:00:00.000000-09:00" , verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitek_card',
            name='acreated_by',
            field=models.ForeignKey(db_column='created_by', default='orgdb', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitek_card_created_by', to='apputil.applicationuser', verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitek_card',
            name='adeleted_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='vitek_card',
            name='adeleted_by',
            field=models.ForeignKey(db_column='deleted_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitek_card_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='vitek_card',
            name='aupdated_by',
            field=models.ForeignKey(db_column='updated_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitek_card_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='vitek_id',
            name='acreated_at',
            field=models.DateTimeField(auto_now_add=True, default="2022-11-28 06:00:00.000000-09:00" , verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitek_id',
            name='acreated_by',
            field=models.ForeignKey(db_column='created_by', default='orgdb', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitek_id_created_by', to='apputil.applicationuser', verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitek_id',
            name='adeleted_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='vitek_id',
            name='adeleted_by',
            field=models.ForeignKey(db_column='deleted_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitek_id_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='vitek_id',
            name='aupdated_by',
            field=models.ForeignKey(db_column='updated_by', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitek_id_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
    ]
