# Generated by Django 4.1.3 on 2023-05-23 22:01

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apputil', '0001_initial'),
        ('ddrug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drug_note',
            field=models.CharField(blank=True, max_length=50, verbose_name='Drug Note'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_othernames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60), null=True, size=30, verbose_name='Other Names'),
        ),
        migrations.CreateModel(
            name='Breakpoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('org_name', models.CharField(max_length=50, verbose_name='Organism')),
                ('notorg_name', models.CharField(max_length=50, verbose_name='Not(Organism)')),
                ('med_application', models.CharField(max_length=50, verbose_name='Application')),
                ('bp_res_gt', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='>Res')),
                ('bp_sens_le', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='<=Sens')),
                ('bp_unit', models.CharField(max_length=5, verbose_name='Unit')),
                ('bp_comb', models.CharField(max_length=20, verbose_name='Combination')),
                ('bp_source', models.CharField(max_length=50, verbose_name='BP Source')),
                ('bp_source_version', models.CharField(max_length=50, verbose_name='BP Version')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('bp_type', models.ForeignKey(blank=True, db_column='bp_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_bptype', to='apputil.dictionary', verbose_name='BP Type')),
                ('drug_id', models.ForeignKey(db_column='drug_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_drug_id', to='ddrug.drug', verbose_name='Drug ID')),
                ('notorg_rank', models.ForeignKey(blank=True, db_column='notorg_rank', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_notorgtype', to='apputil.dictionary', verbose_name='Not(Rank)')),
                ('org_rank', models.ForeignKey(blank=True, db_column='org_rank', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_orgtype', to='apputil.dictionary', verbose_name='Rank')),
            ],
            options={
                'db_table': 'breakpoints',
                'ordering': ['drug_id', 'org_rank', 'org_name', 'bp_type'],
            },
        ),
        migrations.AddIndex(
            model_name='breakpoints',
            index=models.Index(fields=['drug_id'], name='bp_drug_idx'),
        ),
        migrations.AddIndex(
            model_name='breakpoints',
            index=models.Index(fields=['org_name'], name='bp_org_idx'),
        ),
        migrations.AddIndex(
            model_name='breakpoints',
            index=models.Index(fields=['notorg_rank'], name='bp_nrnk_idx'),
        ),
        migrations.AddIndex(
            model_name='breakpoints',
            index=models.Index(fields=['notorg_name'], name='bp_norg_idx'),
        ),
        migrations.AddIndex(
            model_name='breakpoints',
            index=models.Index(fields=['org_rank'], name='bp_ornk_idx'),
        ),
        migrations.AddIndex(
            model_name='breakpoints',
            index=models.Index(fields=['bp_source'], name='bp_src_idx'),
        ),
        migrations.AddIndex(
            model_name='breakpoints',
            index=models.Index(fields=['bp_type'], name='bp_btyp_idx'),
        ),
    ]
