# Generated by Django 4.1.3 on 2023-03-20 09:57

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dscreen', '0001_initial'),
        ('ddrug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coadd_bmd',
            name='run_id',
            field=models.ForeignKey(blank=True, db_column='run_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_RunID+', to='dscreen.screen_run', verbose_name='Run ID'),
        ),
        migrations.AddIndex(
            model_name='vitek_id',
            index=models.Index(fields=['card_barcode'], name='vid_barcode_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_id',
            index=models.Index(fields=['id_organism'], name='vid_idorg_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_id',
            index=models.Index(fields=['id_probability'], name='vid_idprob_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_id',
            index=models.Index(fields=['id_confidence'], name='vid_idconf_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_id',
            index=models.Index(fields=['filename'], name='vid_fname_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_card',
            index=models.Index(fields=['card_type'], name='vcard_ctype_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_card',
            index=models.Index(fields=['card_code'], name='vcard_ccode_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_card',
            index=models.Index(fields=['card_barcode'], name='vcard_bcode_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_card',
            index=models.Index(fields=['orgbatch_id'], name='vcard_orgbatch_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_ast',
            index=models.Index(fields=['drug_id'], name='vast_drugid_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_ast',
            index=models.Index(fields=['mic'], name='vast_mic_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_ast',
            index=models.Index(fields=['bp_profile'], name='vast_bprofile_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_ast',
            index=models.Index(fields=['bp_source'], name='vast_bpsource_idx'),
        ),
        migrations.AddIndex(
            model_name='vitek_ast',
            index=models.Index(fields=['filename'], name='vast_fname_idx'),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['drug_name'], name='drug_dname_idx'),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=django.contrib.postgres.indexes.GistIndex(fields=['smol'], name='drug_smol_idx'),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=django.contrib.postgres.indexes.GistIndex(fields=['ffp2'], name='drug_ffp2_idx'),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=django.contrib.postgres.indexes.GistIndex(fields=['mfp2'], name='drug_mfp2_idx'),
        ),
    ]
