# Generated by Django 4.1.3 on 2023-05-24 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddrug', '0002_alter_drug_drug_note_alter_drug_drug_othernames_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='breakpoints',
            table='breakpoint',
        ),
    ]
