# Generated by Django 3.2.6 on 2022-12-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddrug', '0002_auto_20221130_1010'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vitek_ast',
            table='vitek_ast',
        ),
        migrations.AlterModelTable(
            name='vitek_card',
            table='vitek_card',
        ),
        migrations.AlterModelTable(
            name='vitek_id',
            table='vitek_id',
        ),
    ]
