# Generated by Django 4.1.5 on 2023-03-06 00:18

import django.contrib.postgres.indexes
from django.db import migrations
import django_rdkit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ddrug', '0002_alter_vitek_ast_options_alter_vitek_id_id_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='mfp2',
            field=django_rdkit.models.fields.BfpField(null=True, verbose_name='MFP2'),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=django.contrib.postgres.indexes.GistIndex(fields=['mfp2'], name='drug_mfp2_idx'),
        ),
    ]
