# Generated by Django 4.2.2 on 2024-03-24 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddrug', '0003_alter_vitek_ast_organism_alter_vitek_card_instrument'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='drug',
            name='drug_smol_idx',
        ),
        migrations.RemoveIndex(
            model_name='drug',
            name='drug_ffp2_idx',
        ),
        migrations.RemoveIndex(
            model_name='drug',
            name='drug_mfp2_idx',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='ffp2',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='mfp2',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='smol',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='torsionbv',
        ),
    ]
