# Generated by Django 4.1.5 on 2023-03-06 00:50

from django.db import migrations
import django_rdkit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ddrug', '0003_drug_mfp2_drug_drug_mfp2_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='torsionbv',
            field=django_rdkit.models.fields.BfpField(null=True),
        ),
    ]
