# Generated by Django 4.1.3 on 2023-05-24 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddrug', '0003_alter_breakpoints_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Breakpoints',
        ),
    ]
