# Generated by Django 4.1.5 on 2023-03-06 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddrug', '0004_drug_torsionbv'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='drug',
            name='drug_mfp2_idx',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='mfp2',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='torsionbv',
        ),
    ]
