# Generated by Django 4.2.2 on 2024-05-21 02:44

from django.db import migrations, models
import django_rdkit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ddrug', '0004_remove_drug_drug_smol_idx_remove_drug_drug_ffp2_idx_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='drug',
        #     name='ffp2',
        #     field=django_rdkit.models.fields.BfpField(null=True, verbose_name='FFP2'),
        # ),
        # migrations.AddField(
        #     model_name='drug',
        #     name='mfp2',
        #     field=django_rdkit.models.fields.BfpField(null=True, verbose_name='MFP2'),
        # ),
        # migrations.AddField(
        #     model_name='drug',
        #     name='salt_form',
        #     field=models.CharField(blank=True, max_length=15, verbose_name='SaltForm'),
        # ),
        # migrations.AddField(
        #     model_name='drug',
        #     name='smol',
        #     field=django_rdkit.models.fields.MolField(blank=True, null=True, verbose_name='MOL'),
        # ),
        # migrations.AddField(
        #     model_name='drug',
        #     name='torsionbv',
        #     field=django_rdkit.models.fields.BfpField(null=True),
        # ),
    ]
