# Generated by Django 4.1.3 on 2023-05-24 23:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ddrug', '0005_breakpoints_breakpoints_bp_drug_idx_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Breakpoints',
            new_name='Breakpoint',
        ),
    ]
