# Generated by Django 4.1.5 on 2023-03-07 00:02

import django.contrib.postgres.indexes
from django.db import migrations
import django_rdkit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ddrug', '0005_remove_drug_drug_mfp2_idx_remove_drug_mfp2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='mfp2',
            field=django_rdkit.models.fields.BfpField(null=True, verbose_name='MFP2'),
        ),
        migrations.AddField(
            model_name='drug',
            name='torsionbv',
            field=django_rdkit.models.fields.BfpField(null=True),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=django.contrib.postgres.indexes.GistIndex(fields=['mfp2'], name='drug_mfp2_idx'),
        ),
    ]
