# Generated by Django 4.1.3 on 2022-11-29 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddrug', '0005_alter_drug_acreated_by_alter_vitek_ast_acreated_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='acreated_by',
            new_name='acreated',
        ),
        migrations.RenameField(
            model_name='vitek_ast',
            old_name='acreated_by',
            new_name='acreated',
        ),
        migrations.RenameField(
            model_name='vitek_card',
            old_name='acreated_by',
            new_name='acreated',
        ),
        migrations.RenameField(
            model_name='vitek_id',
            old_name='acreated_by',
            new_name='acreated',
        ),
    ]
