# Generated by Django 4.1.5 on 2023-03-20 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dscreen', '0001_initial'),
        ('apputil', '0009_alter_applicationlog_options_dictionary_dict_sort_and_more'),
        ('dorganism', '0008_alter_organism_options'),
        ('ddrug', '0006_drug_mfp2_drug_torsionbv_drug_drug_mfp2_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='COADD_BMD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('mic', models.CharField(blank=True, max_length=50, verbose_name='MIC')),
                ('mic_unit', models.CharField(blank=True, max_length=20, verbose_name='Unit')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('drug_id', models.ForeignKey(db_column='drug_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_drug_id+', to='ddrug.drug', verbose_name='Drug ID')),
                ('media', models.ForeignKey(blank=True, db_column='media', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_Media+', to='apputil.dictionary', verbose_name='Media')),
                ('mic_type', models.ForeignKey(blank=True, db_column='mic_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_MICType+', to='apputil.dictionary', verbose_name='MIC Type')),
                ('orgbatch_id', models.ForeignKey(db_column='orgbatch_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_orgbatch_id+', to='dorganism.organism_batch', verbose_name='OrgBatch ID')),
                ('plate_material', models.ForeignKey(blank=True, db_column='plate_material', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_PlateMaterial+', to='apputil.dictionary', verbose_name='Plate Material')),
                ('plate_size', models.ForeignKey(blank=True, db_column='plate_size', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_PlateSize+', to='apputil.dictionary', verbose_name='Plate Size')),
                ('run_id', models.ForeignKey(blank=True, db_column='run_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_RunID+', to='dscreen.screen_run', verbose_name='Run ID')),
            ],
            options={
                'db_table': 'coadd_bmd',
                'ordering': ['drug_id', 'orgbatch_id'],
            },
        ),
    ]
