# Generated by Django 4.1.3 on 2023-05-24 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddrug', '0006_rename_breakpoints_breakpoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Breakpoint',
        ),
    ]
