# Generated by Django 4.1.5 on 2023-04-12 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0010_alter_applicationlog_log_user'),
        ('dorganism', '0014_alter_organism_biologist_and_more'),
        ('ddrug', '0007_mic_coadd_mic_pub_vitek_ast_vast_orgname_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drug_type',
            field=models.ForeignKey(blank=True, db_column='drug_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_drugtype', to='apputil.dictionary', verbose_name='Drug Type'),
        ),
        migrations.AlterField(
            model_name='mic_coadd',
            name='drug_id',
            field=models.ForeignKey(db_column='drug_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_drug_id', to='ddrug.drug', verbose_name='Drug ID'),
        ),
        migrations.AlterField(
            model_name='mic_coadd',
            name='mic_type',
            field=models.ForeignKey(blank=True, db_column='mic_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mictype', to='apputil.dictionary', verbose_name='MIC Type'),
        ),
        migrations.AlterField(
            model_name='mic_coadd',
            name='orgbatch_id',
            field=models.ForeignKey(db_column='orgbatch_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_orgbatch_id', to='dorganism.organism_batch', verbose_name='OrgBatch ID'),
        ),
        migrations.AlterField(
            model_name='mic_coadd',
            name='plate_material',
            field=models.ForeignKey(blank=True, db_column='plate_material', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_material', to='apputil.dictionary', verbose_name='Plate Material'),
        ),
        migrations.AlterField(
            model_name='mic_coadd',
            name='plate_size',
            field=models.ForeignKey(blank=True, db_column='plate_size', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_platesize', to='apputil.dictionary', verbose_name='Plate Size'),
        ),
        migrations.AlterField(
            model_name='mic_pub',
            name='drug_id',
            field=models.ForeignKey(db_column='drug_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_drug_id', to='ddrug.drug', verbose_name='Drug ID'),
        ),
        migrations.AlterField(
            model_name='mic_pub',
            name='mic_type',
            field=models.ForeignKey(blank=True, db_column='mic_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mictype', to='apputil.dictionary', verbose_name='MIC Type'),
        ),
        migrations.AlterField(
            model_name='mic_pub',
            name='organism_id',
            field=models.ForeignKey(db_column='oragnism_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_organism_id', to='dorganism.organism', verbose_name='Organism ID'),
        ),
        migrations.AlterField(
            model_name='vitek_ast',
            name='card_barcode',
            field=models.ForeignKey(db_column='card_barcode', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_card_barcode', to='ddrug.vitek_card', verbose_name='Card Barcode'),
        ),
        migrations.AlterField(
            model_name='vitek_ast',
            name='drug_id',
            field=models.ForeignKey(db_column='drug_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_drug_id', to='ddrug.drug', verbose_name='Drug ID'),
        ),
        migrations.AlterField(
            model_name='vitek_card',
            name='card_type',
            field=models.ForeignKey(blank=True, db_column='card_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_cardtype', to='apputil.dictionary', verbose_name='Card Type'),
        ),
        migrations.AlterField(
            model_name='vitek_card',
            name='orgbatch_id',
            field=models.ForeignKey(db_column='orgbatch_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_orgbatch_id', to='dorganism.organism_batch', verbose_name='OrgBatch ID'),
        ),
        migrations.AlterField(
            model_name='vitek_id',
            name='card_barcode',
            field=models.ForeignKey(db_column='card_barcode', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_card_barcode', to='ddrug.vitek_card', verbose_name='Card Barcode'),
        ),
    ]
