# Generated by Django 4.1.3 on 2022-11-29 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddrug', '0007_alter_drug_adeleted_by_alter_drug_aupdated_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='adeleted_by',
            new_name='adeleted',
        ),
        migrations.RenameField(
            model_name='drug',
            old_name='aupdated_by',
            new_name='aupdated',
        ),
        migrations.RenameField(
            model_name='vitek_ast',
            old_name='adeleted_by',
            new_name='adeleted',
        ),
        migrations.RenameField(
            model_name='vitek_ast',
            old_name='aupdated_by',
            new_name='aupdated',
        ),
        migrations.RenameField(
            model_name='vitek_card',
            old_name='adeleted_by',
            new_name='adeleted',
        ),
        migrations.RenameField(
            model_name='vitek_card',
            old_name='aupdated_by',
            new_name='aupdated',
        ),
        migrations.RenameField(
            model_name='vitek_id',
            old_name='adeleted_by',
            new_name='adeleted',
        ),
        migrations.RenameField(
            model_name='vitek_id',
            old_name='aupdated_by',
            new_name='aupdated',
        ),
    ]
