# Generated by Django 4.1.5 on 2023-03-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddrug', '0007_coadd_bmd'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vitek_ast',
            index=models.Index(fields=['organism'], name='vast_orgname_idx'),
        ),
    ]
