# Generated by Django 4.1.5 on 2023-04-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddrug', '0008_alter_drug_drug_type_alter_mic_coadd_drug_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mic_pub',
            name='zone_diameter',
            field=models.CharField(blank=True, max_length=20, verbose_name='Zone Diameter'),
        ),
    ]
