# Generated by Django 4.1.3 on 2023-06-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddrug', '0008_breakpoint_breakpoint_bp_drug_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakpoint',
            name='bp_comb',
            field=models.CharField(blank=True, max_length=20, verbose_name='Combination'),
        ),
        migrations.AlterField(
            model_name='breakpoint',
            name='med_application',
            field=models.CharField(blank=True, max_length=50, verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='breakpoint',
            name='notorg_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Not(Organism)'),
        ),
        migrations.AlterField(
            model_name='breakpoint',
            name='org_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Organism'),
        ),
    ]
