# Generated by Django 4.1.5 on 2023-06-05 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddrug', '0009_alter_breakpoint_bp_comb_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitek_id',
            options={'ordering': ['card_barcode']},
        ),
    ]
