# Generated by Django 4.1.1 on 2023-04-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddrug', '0009_mic_pub_zone_diameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drug_name',
            field=models.CharField(max_length=50, verbose_name='Drug Name'),
        ),
    ]
