# Generated by Django 4.2.1 on 2023-07-06 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dscreen', '__first__'),
        ('ddrug', '0010_alter_vitek_id_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mic_coadd',
            name='run_id',
            field=models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_run_id', to='dscreen.screen_run', verbose_name='Run ID'),
        ),
    ]
