# Generated by Django 4.2.1 on 2023-07-11 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorganism', '0019_alter_organism_batch_biologist_and_more'),
        ('ddrug', '0011_alter_mic_coadd_run_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drug_subclass',
            field=models.CharField(blank=True, max_length=100, verbose_name='SubClass'),
        ),
        migrations.AlterField(
            model_name='mic_pub',
            name='organism_id',
            field=models.ForeignKey(db_column='organism_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_organism_id', to='dorganism.organism', verbose_name='Organism ID'),
        ),
    ]
