
#from django_rdkit import models
from django.db import models
import re

#from django_rdkit import models
from django.db import models
from model_utils import Choices
from sequences import Sequence
from django.core.validators import RegexValidator

from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.indexes import GinIndex
from django.core.validators import MaxValueValidator, MinValueValidator 
from django.db import transaction, IntegrityError
from django.utils.text import slugify

from apputil.models import AuditModel, Dictionary, ApplicationUser, Document
from apputil.utils.data import strList_to_List, split_StrList
from ddrug.utils.bio_data import pScore, ActScore_DR, ActScore_SC
from dsample.models import CmpBatchList_Base, Compound_Batch
from dcell.models import Cell
from dorganism.models import Organism
from adjcoadd.constants import *

import logging
logger = logging.getLogger(__name__)

#-------------------------------------------------------------------------------------------------
# Screening Application Model
#-------------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------------
class Screen_Run(AuditModel):
    """
    List of Screening runs
    """
#-------------------------------------------------------------------------------------------------
    HEADER_FIELDS = {
        "run_id":"Run ID",
        "run_type":"Run Type",
        "assay_note":"Assay",
        "run_status":"Status",
        "run_project":"Project",
        "run_name":"Name",
        "run_date":"Run Date",
        "run_conditions":"Conditions",
        "run_issues":"Issues",
    }

    Choice_Dictionary = {
        'run_type':'Run_Type',
        'run_status':'Process_Status',
    }

    run_id = models.CharField(max_length=15,primary_key=True, verbose_name = "Run ID")
    run_name = models.CharField(max_length=500, blank=True, verbose_name = "Run Name")
    run_type = models.ForeignKey(Dictionary, null=True, blank=True, verbose_name = "Run Type", on_delete=models.DO_NOTHING,
        db_column="run_type", related_name="%(class)s_RunType+")
    assay_note = models.CharField(max_length=250, blank=True, verbose_name = "Assay Note")
    run_conditions = models.CharField(max_length=250, blank=True, verbose_name = "Run Conditions")
    run_issues = models.CharField(max_length=250, blank=True, verbose_name = "Run Issues")
    run_date = models.DateField(null=True, blank=True, verbose_name = "Run Date")
    run_project = models.CharField(max_length=50, verbose_name = "Project")
    run_status = models.ForeignKey(Dictionary, null=True, blank=True, verbose_name = "Run Status", on_delete=models.DO_NOTHING,
        db_column="run_status", related_name="%(class)s_run_status+")
    
    # Summary Data -  to be generated by self.update_summary()
    n_compounds = models.SmallIntegerField(default=0, verbose_name = "#Cpmds")
    n_qc = models.SmallIntegerField(default=0, verbose_name = "#QC")
    n_structure = models.SmallIntegerField(default=0, verbose_name = "#Struc")
    n_motherplates = models.SmallIntegerField(default=0, verbose_name = "#MP")
    n_testplates = models.SmallIntegerField(default=0, verbose_name = "#TP")
    n_assays = models.SmallIntegerField(default=0, verbose_name = "#Assays")
    n_inhibitions = models.SmallIntegerField(default=0, verbose_name = "#Inhib")
    n_mic = models.SmallIntegerField(default=0, verbose_name = "#MIC")
    n_cc50 = models.SmallIntegerField(default=0, verbose_name = "#CC50")
    n_hc50 = models.SmallIntegerField(default=0, verbose_name = "#HC50")
    n_synmic = models.SmallIntegerField(default=0, verbose_name = "#synMIC")
    screen_date = models.DateField(null=True, blank=True, verbose_name="Screen")

    #------------------------------------------------
    class Meta:
        app_label = 'dscreen'
        db_table = 'screen_run'
        ordering=['run_type','run_id']
        indexes = [
            models.Index(name="run_type_idx", fields=['run_type']),
        ]

    # #------------------------------------------------
    # def __str__(self) -> str:
    #     return f"{self.run_id}"

    #------------------------------------------------
    def __repr__(self) -> str:
        return f"{self.run_id} [{self.run_type}]"

    #------------------------------------------------
    @classmethod
    def get(cls,RunID,verbose=0):
        try:
            retInstance = cls.objects.get(run_id=RunID)
        except:
            if verbose:
                print(f"[Run_ID Not Found] {RunID} ")
            retInstance = None
        return(retInstance)

    #------------------------------------------------
    @classmethod
    def exists(cls,RunID,verbose=0):
        return cls.objects.filter(run_id=RunID.strip()).exists()
    
    #------------------------------------------------
    def update_summary(self):
        print('To be implemented')
        # self.n_compounds = 
        # self.n_qc = 
        # self.n_structure = 
        # self.n_motherplates = 
        # self.n_testplates = 
        # self.n_assays = 
        # self.n_inhibitions = 
        # self.n_mic = 
        # self.n_cc50 = 
        # self.n_hc50 = 
        # self.n_synmic = 
        # self.screen_date = 

#-------------------------------------------------------------------------------------------------
class Assay(AuditModel):
    """
    List of Assays
    """
#-------------------------------------------------------------------------------------------------
    HEADER_FIELDS = {
        # "run_id":"Run ID",
        # "run_type":"Run Type",
        # "assay_note":"Assay",
        # "run_status":"Status",
        # "run_project":"Project",
        # "run_name":"Name",
        # "run_date":"Run Date",
        # "run_conditions":"Conditions",
        # "run_issues":"Issues",
    }

    Choice_Dictionary = {
        # 'run_type':'Run_Type',
        # 'run_status':'Process_Status',
    }

    assay_id = models.CharField(max_length=100,primary_key=True, verbose_name = "Assay ID")
    ora_assay_id = models.CharField(max_length=100,blank=True, verbose_name = "Ora Assay ID")
    assay_type = models.CharField(max_length=30, verbose_name = "AssayType" )
    assay_subtype = models.CharField(max_length=50, verbose_name = "AssaySubType" )
    sum_assay_id  = models.CharField(max_length=100, blank=True, verbose_name = "Assay ID for Summary")
    coadd_assay_id  = models.CharField(max_length=15, blank=True, verbose_name = "COADD Assay ID")
    assay_note = models.CharField(max_length=150, blank=True, verbose_name = "Assay Note")
    assay_code = models.CharField(max_length=20, blank=True, verbose_name = "Assay Code")
    test_media = models.CharField(max_length=150, blank=True, verbose_name = "Media")
    test_dye = models.CharField(max_length=150, blank=True, verbose_name = "Dye/Kit")
    test_enviroment = models.CharField(max_length=150, blank=True, verbose_name = "Enviroment")
    test_temperature = models.CharField(max_length=150, blank=True, verbose_name = "Temp")
    test_time = models.CharField(max_length=25, blank=True, verbose_name = "Time")
    test_additive = models.CharField(max_length=150, blank=True, verbose_name = "Additive")
    subculture_type = models.CharField(max_length=25, blank=True, verbose_name = "Subculture/Seeding")
    incubation_time = models.CharField(max_length=25, blank=True, verbose_name = "Incubation Time")

    organism_id = models.ForeignKey(Organism, null=True, blank=True, verbose_name = "Organism ID", on_delete=models.DO_NOTHING,
        db_column="organism_id", related_name="%(class)s_organism_id")
    cell_id = models.ForeignKey(Cell, null=True, blank=True, verbose_name = "Cell ID", on_delete=models.DO_NOTHING,
        db_column="cell_id", related_name="%(class)s_cellid")
    
    source = models.CharField(max_length=250, blank=True, verbose_name = "Source")
    source_code = models.CharField(max_length=120, blank=True, verbose_name = "Source Code")
    reference = models.CharField(max_length=150, blank=True, verbose_name = "Reference")

    #------------------------------------------------
    class Meta:
        app_label = 'dscreen'
        db_table = 'assay'
        ordering=['assay_id']
        indexes = [
            models.Index(name="ass_aid_idx", fields=['assay_id']),
            models.Index(name="ass_aty_idx", fields=['assay_type']),
            models.Index(name="ass_sid_idx", fields=['sum_assay_id']),
        ]

    # #------------------------------------------------
    # def __str__(self) -> str:
    #     return f"{self.run_id}"

    #------------------------------------------------
    def __repr__(self) -> str:
        return f"{self.run_id} [{self.run_type}]"

    #------------------------------------------------
    @classmethod
    def get(cls,AssayID,verbose=0):
        try:
            retInstance = cls.objects.get(assay_id=AssayID)
        except:
            if verbose:
                print(f"[Assay_ID Not Found] {AssayID} ")
            retInstance = None
        return(retInstance)

    #------------------------------------------------
    @classmethod
    def exists(cls,AssayID,verbose=0):
        return cls.objects.filter(assay_id=AssayID).exists()
    
#-------------------------------------------------------------------------------------------------
class AssayData_MIC(CmpBatchList_Base):
    """
    List of MIC Values
    """
#-------------------------------------------------------------------------------------------------
    from dplate.models import TestPlate
#    from dorganism.models import Organism, Organism_Batch


    HEADER_FIELDS = {
        # "run_id":"Run ID",
        # "run_type":"Run Type",
        # "assay_note":"Assay",
        # "run_status":"Status",
        # "run_project":"Project",
        # "run_name":"Name",
        # "run_date":"Run Date",
        # "run_conditions":"Conditions",
        # "run_issues":"Issues",
    }

    Choice_Dictionary = {
        'pub_status':'Pub_Status',
    }
    
    # Primary Contraint
    testplate_id = models.ForeignKey(TestPlate, blank=False, verbose_name = "TestPlate ID", on_delete=models.DO_NOTHING,
        db_column="testplate_id", related_name="%(class)s_testplateid")
    testwell_id = models.CharField(max_length=5, blank=True, verbose_name = "TestWell ID")

    assay_id = models.ForeignKey(Assay, null=True, blank=True, verbose_name = "Assay ID", on_delete=models.DO_NOTHING,
        db_column="assay_id", related_name="%(class)s_assay_id")
    ora_assay_id = models.CharField(max_length=25, blank=True, verbose_name = "ora Assay ID")

    run_id = models.ForeignKey(Screen_Run, null=False, blank=False, verbose_name = "Run ID", on_delete=models.DO_NOTHING,
        db_column="run_id", related_name="%(class)s_run_id") 

    # Plate Information ----------------------------------------------------------------------------
    # test_date = models.DateField(null=True, blank=True, verbose_name = "Date")
    # plate_size = models.ForeignKey(Dictionary, null=True, blank=True, verbose_name = "Plate Size", on_delete=models.DO_NOTHING,
    #     db_column="plate_size", related_name="%(class)s_platesize")
    # plate_material = models.ForeignKey(Dictionary, null=True, blank=True, verbose_name = "Plate Material", on_delete=models.DO_NOTHING,
    #     db_column="plate_material", related_name="%(class)s_material")
    # orgbatch_id = models.ForeignKey(Organism_Batch, null=False, blank=False, verbose_name = "OrgBatch ID", on_delete=models.DO_NOTHING,
    #     db_column="orgbatch_id", related_name="%(class)s_orgbatch_id") 
    # test_media = models.CharField(max_length=40, blank=True, verbose_name = "Media")
    # test_dye = models.CharField(max_length=40, blank=True, verbose_name = "Dye")
    # test_additive = models.CharField(max_length=80, blank=True, verbose_name = "Additive")
    # readout_type = models.CharField(max_length=25, blank=True, verbose_name = "Readout Type")

    mic = models.CharField(max_length=50, verbose_name = "MIC")
    mic_unit = models.CharField(max_length=20, verbose_name = "Unit")
    mic_skips = models.SmallIntegerField(default=0, blank=True, verbose_name = "Skips")

    act_type = models.CharField(max_length=5, blank=True, verbose_name = "Act Type")
    act_score = models.SmallIntegerField(default=-1, blank=True, verbose_name = "Act Score")
    pscore = models.DecimalField(default=-1, max_digits=10, decimal_places=2, verbose_name = "pScore")

    analysis = models.CharField(max_length=15, verbose_name = "Analysis")

    inhibit_max = models.DecimalField(max_digits=10, decimal_places=2, verbose_name = "DMax")
    inhibit_min = models.DecimalField(max_digits=10, decimal_places=2, verbose_name = "DMin")
    conc_max = models.DecimalField(max_digits=12, decimal_places=4, verbose_name = "CMax")
    conc_min = models.DecimalField(max_digits=12, decimal_places=4, verbose_name = "CMin")
    n_conc = models.SmallIntegerField(default=-1, blank=True, verbose_name = "#Conc")
    data_quality = models.CharField(max_length=50, verbose_name = "Data Quality")
    valid = models.SmallIntegerField(default=-1, blank=True, verbose_name = "Valid")

    ref_mic = models.CharField(max_length=150, blank=True, verbose_name = "Ref MIC")
    ref_mic_chk = models.SmallIntegerField(default=-1, blank=True, verbose_name = "d(Dilution)")
    ic50 = models.CharField(max_length=50, blank=True, verbose_name = "IC50")
    ic50_unit = models.CharField(max_length=20, blank=True, verbose_name = "IC50 Unit")
    ic50_pscore = models.DecimalField(default=-1, max_digits=10, decimal_places=2, verbose_name = "IC50 pScore")
    ic50_quality = models.CharField(max_length=20, blank=True, verbose_name = "IC50 Quality")
    ic50_r2 = models.DecimalField(default=-1, max_digits=10, decimal_places=2, verbose_name = "IC50 r2")
    ic50_slope = models.DecimalField(max_digits=12, decimal_places=4, verbose_name = "IC50 Slope")

    pub_status = models.ForeignKey(Dictionary, null=True, blank=True, verbose_name = "Pub Status", on_delete=models.DO_NOTHING,
        db_column="pub_status", related_name="%(class)s_pub_statust")
    pub_date = models.DateField(null=True, blank=True,  editable=False, verbose_name="Published")
    chk_migration = models.SmallIntegerField(default=-1, blank=False, verbose_name = "Check for migration")

    class Meta:
        app_label = 'dscreen'
        db_table = 'assaydata_mic'
        ordering=['assay_id','testplate_id','testwell_id']
        constraints = [
            models.UniqueConstraint(name='assmic_loc_cst', fields=['testplate_id', 'testwell_id'], )
        ]        
        indexes = [
            GinIndex(name="assmic_cmp_idx",fields=['cmpbatch_lst']),
            models.Index(name="assmic_rid_idx",fields=['run_id']),
            models.Index(name="assmic_sid_idx",fields=['assay_id']),
            models.Index(name="assmic_asc_idx",fields=['act_score']),
            models.Index(name="assmic_ana_idx",fields=['analysis']),
        #    models.Index(name="assmic_rot_idx",fields=['readout_type']),
            models.Index(name="assmic_act_idx",fields=['act_type']),
            models.Index(name="assmic_psc_idx",fields=['pscore']),
            models.Index(name="assmic_val_idx",fields=['valid']),
            models.Index(name="assmic_dqy_idx",fields=['data_quality']),
            models.Index(name="assmic_chkm_idx",fields=['chk_migration']),
        ]

    #------------------------------------------------
    @classmethod
    def get(cls,PlateID,WellID,verbose=0):
        try:
            retInstance = cls.objects.get(testplate_id=PlateID, testwell_id=WellID)
        except:
            if verbose:
                logger.warning(f"[AssayData Not Found] {PlateID} {WellID}")
            retInstance = None
        return(retInstance)

    #------------------------------------------------
    # Returns an User instance if found by name
    @classmethod
    def exists(cls,PlateID,WellID):
        return cls.objects.filter(testplate_id=PlateID, testwell_id=WellID).exists()

    #------------------------------------------------  
    def conv_list_to_string(self):
        super().conv_list_to_string()
        self.mic_lst        = COMPOUND_SEP.join([str(x) for x in self.mic if x > 0])
        self.mic_unit_lst   = COMPOUND_SEP.join([str(x) for x in self.mic_unit if x > 0])

    #------------------------------------------------  
    def conv_string_to_lst(self):
        super().conv_string_to_list()
        self.mic = strList_to_List(self.mic_lst,sep=COMPOUND_SEP,size=4,fill="")
        self.mic_unit = strList_to_List(self.mic_unit_lst,sep=COMPOUND_SEP,size=4,fill="")

   #------------------------------------------------
    def set_actscores(self,verbose=0):
        self.act_score = ActScore_DR(self.mic,self.mic_unit,DMax=self.inhibit_max)
        self.pscore = pScore(self.mic,self.mic_unit,self.inhibit_max,MW=self.cmpbatch_id.full_mw,gtShift=3,drMax2=40)    

#-------------------------------------------------------------------------------------------------
class AssayData_CC50(CmpBatchList_Base):
    """
    List of Cytotoxicty Values
    """
#-------------------------------------------------------------------------------------------------
    from dplate.models import TestPlate

    HEADER_FIELDS = {
        # "run_id":"Run ID",
    }

    Choice_Dictionary = {
        'pub_status':'Pub_Status',
    }
        
    # Primary Contraint
    testplate_id = models.ForeignKey(TestPlate, blank=False, verbose_name = "TestPlate ID", on_delete=models.DO_NOTHING,
        db_column="testplate_id", related_name="%(class)s_testplateid")
    testwell_id = models.CharField(max_length=5, blank=True, verbose_name = "TestWell ID")

    assay_id = models.ForeignKey(Assay, null=True, blank=True, verbose_name = "Assay ID", on_delete=models.DO_NOTHING,
        db_column="assay_id", related_name="%(class)s_assay_id")
    ora_assay_id = models.CharField(max_length=25, blank=True, verbose_name = "ora Assay ID")

    run_id = models.ForeignKey(Screen_Run, null=False, blank=False, verbose_name = "Run ID", on_delete=models.DO_NOTHING,
        db_column="run_id", related_name="%(class)s_run_id") 

    cc50 = models.CharField(max_length=50, blank=True, verbose_name = "CC50")
    cc50_unit = models.CharField(max_length=20, blank=True, verbose_name = "CC50 Unit")
    cc50_pscore = models.DecimalField(default=-1, max_digits=10, decimal_places=2, verbose_name = "CC50 pScore")
    cc50_quality = models.CharField(max_length=20, blank=True, verbose_name = "CC50 Quality")
    cc50_r2 = models.DecimalField(default=-1, max_digits=10, decimal_places=2, verbose_name = "CC50 r2")
    cc50_slope = models.DecimalField(max_digits=12, decimal_places=4, verbose_name = "CC50 Slope")

    act_type = models.CharField(max_length=5, blank=True, verbose_name = "Act Type")
    act_score = models.SmallIntegerField(default=-1, blank=True, verbose_name = "Act Score")
    pscore = models.DecimalField(default=-1, max_digits=10, decimal_places=2, verbose_name = "pScore")

    analysis = models.CharField(max_length=15, verbose_name = "Analysis")

    inhibit_max = models.DecimalField(max_digits=10, decimal_places=2, verbose_name = "DMax")
    inhibit_min = models.DecimalField(max_digits=10, decimal_places=2, verbose_name = "DMin")
    conc_max = models.DecimalField(max_digits=12, decimal_places=4, verbose_name = "CMax")
    conc_min = models.DecimalField(max_digits=12, decimal_places=4, verbose_name = "CMin")
    n_conc = models.SmallIntegerField(default=-1, blank=True, verbose_name = "#Conc")
    data_quality = models.CharField(max_length=50, verbose_name = "Data Quality")
    valid = models.SmallIntegerField(default=-1, blank=True, verbose_name = "Valid")

    ref_cc50 = models.CharField(max_length=150, blank=True, verbose_name = "Ref MIC")
    ref_cc50_chk = models.SmallIntegerField(default=-1, blank=True, verbose_name = "d(Dilution)")

    pub_status = models.ForeignKey(Dictionary, null=True, blank=True, verbose_name = "Pub Status", on_delete=models.DO_NOTHING,
        db_column="pub_status", related_name="%(class)s_pub_statust")
    pub_date = models.DateField(null=True, blank=True,  editable=False, verbose_name="Published")
    chk_migration = models.SmallIntegerField(default=-1, blank=False, verbose_name = "Check for migration")

    class Meta:
        app_label = 'dscreen'
        db_table = 'assaydata_cc50'
        ordering=['assay_id','testplate_id','testwell_id']
        constraints = [
            models.UniqueConstraint(name='asscc50_loc_cst', fields=['testplate_id', 'testwell_id'], )
        ]        
        indexes = [
            GinIndex(name="asscc50_cmp_idx",fields=['cmpbatch_lst']),
            models.Index(name="asscc50_rid_idx",fields=['run_id']),
            models.Index(name="asscc50_sid_idx",fields=['assay_id']),
            models.Index(name="asscc50_asc_idx",fields=['act_score']),
            models.Index(name="asscc50_ana_idx",fields=['analysis']),
        #    models.Index(name="asscc50_rot_idx",fields=['readout_type']),
            models.Index(name="asscc50_act_idx",fields=['act_type']),
            models.Index(name="asscc50_psc_idx",fields=['pscore']),
            models.Index(name="asscc50_val_idx",fields=['valid']),
            models.Index(name="asscc50_dqy_idx",fields=['data_quality']),
            models.Index(name="asscc50_chkm_idx",fields=['chk_migration']),
        ]

    #------------------------------------------------
    @classmethod
    def get(cls,PlateID,WellID,verbose=0):
        try:
            retInstance = cls.objects.get(testplate_id=PlateID, testwell_id=WellID)
        except:
            if verbose:
                logger.warning(f"[AssayData Not Found] {PlateID} {WellID}")
            retInstance = None
        return(retInstance)

    #------------------------------------------------
    # Returns an User instance if found by name
    @classmethod
    def exists(cls,PlateID,WellID):
        return cls.objects.filter(testplate_id=PlateID, testwell_id=WellID).exists()

    #------------------------------------------------  
    # def conv_list_to_string(self):
    #     super().conv_list_to_string()
    #     self.mic_lst        = COMPOUND_SEP.join([str(x) for x in self.mic if x > 0])
    #     self.mic_unit_lst   = COMPOUND_SEP.join([str(x) for x in self.mic_unit if x > 0])

    #------------------------------------------------  
    # def conv_string_to_lst(self):
    #     super().conv_string_to_list()
    #     self.mic = strList_to_List(self.mic_lst,sep=COMPOUND_SEP,size=4,fill="")
    #     self.mic_unit = strList_to_List(self.mic_unit_lst,sep=COMPOUND_SEP,size=4,fill="")

   #------------------------------------------------
    def set_actscores(self,verbose=0):
        self.act_score = ActScore_DR(self.cc50,self.cc50_unit,DMax=self.inhibit_max)
        self.pscore = pScore(self.cc50,self.cc50_unit,self.inhibit_max,MW=self.cmpbatch_id.full_mw,gtShift=3,drMax2=40)

#-------------------------------------------------------------------------------------------------
class AssayData_HC50(CmpBatchList_Base):
    """
    List of Haemolysis Values
    """
#-------------------------------------------------------------------------------------------------
    from dplate.models import TestPlate

    HEADER_FIELDS = {
        # "run_id":"Run ID",
    }

    Choice_Dictionary = {
        'pub_status':'Pub_Status',
    }
        
    # Primary Contraint
    testplate_id = models.ForeignKey(TestPlate, blank=False, verbose_name = "TestPlate ID", on_delete=models.DO_NOTHING,
        db_column="testplate_id", related_name="%(class)s_testplateid")
    testwell_id = models.CharField(max_length=5, blank=True, verbose_name = "TestWell ID")

    assay_id = models.ForeignKey(Assay, null=True, blank=True, verbose_name = "Assay ID", on_delete=models.DO_NOTHING,
        db_column="assay_id", related_name="%(class)s_assay_id")
    ora_assay_id = models.CharField(max_length=25, blank=True, verbose_name = "ora Assay ID")

    run_id = models.ForeignKey(Screen_Run, null=False, blank=False, verbose_name = "Run ID", on_delete=models.DO_NOTHING,
        db_column="run_id", related_name="%(class)s_run_id") 

    hc50 = models.CharField(max_length=50, blank=True, verbose_name = "HC50")
    hc50_unit = models.CharField(max_length=20, blank=True, verbose_name = "HC50 Unit")
    hc50_pscore = models.DecimalField(default=-1, max_digits=10, decimal_places=2, verbose_name = "HC50 pScore")
    hc50_quality = models.CharField(max_length=20, blank=True, verbose_name = "HC50 Quality")
    hc50_r2 = models.DecimalField(default=-1, max_digits=10, decimal_places=2, verbose_name = "HC50 r2")
    hc50_slope = models.DecimalField(max_digits=12, decimal_places=4, verbose_name = "HC50 Slope")
    hc10 = models.CharField(max_length=50, blank=True, verbose_name = "HC10")

    act_type = models.CharField(max_length=5, blank=True, verbose_name = "Act Type")
    act_score = models.SmallIntegerField(default=-1, blank=True, verbose_name = "Act Score")
    pscore = models.DecimalField(default=-1, max_digits=10, decimal_places=2, verbose_name = "pScore")

    analysis = models.CharField(max_length=15, verbose_name = "Analysis")

    inhibit_max = models.DecimalField(max_digits=10, decimal_places=2, verbose_name = "DMax")
    inhibit_min = models.DecimalField(max_digits=10, decimal_places=2, verbose_name = "DMin")
    conc_max = models.DecimalField(max_digits=12, decimal_places=4, verbose_name = "CMax")
    conc_min = models.DecimalField(max_digits=12, decimal_places=4, verbose_name = "CMin")
    n_conc = models.SmallIntegerField(default=-1, blank=True, verbose_name = "#Conc")
    data_quality = models.CharField(max_length=50, verbose_name = "Data Quality")
    valid = models.SmallIntegerField(default=-1, blank=True, verbose_name = "Valid")

    ref_hc50 = models.CharField(max_length=150, blank=True, verbose_name = "Ref MIC")
    ref_hc50_chk = models.SmallIntegerField(default=-1, blank=True, verbose_name = "d(Dilution)")

    pub_status = models.ForeignKey(Dictionary, null=True, blank=True, verbose_name = "Pub Status", on_delete=models.DO_NOTHING,
        db_column="pub_status", related_name="%(class)s_pub_statust")
    pub_date = models.DateField(null=True, blank=True,  editable=False, verbose_name="Published")
    chk_migration = models.SmallIntegerField(default=-1, blank=False, verbose_name = "Check for migration")

    class Meta:
        app_label = 'dscreen'
        db_table = 'assaydata_hc50'
        ordering=['assay_id','testplate_id','testwell_id']
        constraints = [
            models.UniqueConstraint(name='asshc50_loc_cst', fields=['testplate_id', 'testwell_id'], )
        ]        
        indexes = [
            GinIndex(name="asshc50_cmp_idx",fields=['cmpbatch_lst']),
            models.Index(name="asshc50_rid_idx",fields=['run_id']),
            models.Index(name="asshc50_sid_idx",fields=['assay_id']),
            models.Index(name="asshc50_asc_idx",fields=['act_score']),
            models.Index(name="asshc50_ana_idx",fields=['analysis']),
        #    models.Index(name="asshc50_rot_idx",fields=['readout_type']),
            models.Index(name="asshc50_act_idx",fields=['act_type']),
            models.Index(name="asshc50_psc_idx",fields=['pscore']),
            models.Index(name="asshc50_val_idx",fields=['valid']),
            models.Index(name="asshc50_dqy_idx",fields=['data_quality']),
            models.Index(name="asshc50_chkm_idx",fields=['chk_migration']),
        ]

    #------------------------------------------------
    @classmethod
    def get(cls,PlateID,WellID,verbose=0):
        try:
            retInstance = cls.objects.get(testplate_id=PlateID, testwell_id=WellID)
        except:
            if verbose:
                logger.warning(f"[AssayData Not Found] {PlateID} {WellID}")
            retInstance = None
        return(retInstance)

    #------------------------------------------------
    # Returns an User instance if found by name
    @classmethod
    def exists(cls,PlateID,WellID):
        return cls.objects.filter(testplate_id=PlateID, testwell_id=WellID).exists()

    #------------------------------------------------  
    # def conv_list_to_string(self):
    #     super().conv_list_to_string()
    #     self.mic_lst        = COMPOUND_SEP.join([str(x) for x in self.mic if x > 0])
    #     self.mic_unit_lst   = COMPOUND_SEP.join([str(x) for x in self.mic_unit if x > 0])

    #------------------------------------------------  
    # def conv_string_to_lst(self):
    #     super().conv_string_to_list()
    #     self.mic = strList_to_List(self.mic_lst,sep=COMPOUND_SEP,size=4,fill="")
    #     self.mic_unit = strList_to_List(self.mic_unit_lst,sep=COMPOUND_SEP,size=4,fill="")

   #------------------------------------------------
    def set_actscores(self,verbose=0):
        self.act_score = ActScore_DR(self.hc50,self.hc50_unit,DMax=self.inhibit_max,cutoff_inhib=10)
        self.pscore = pScore(self.hc50,self.hc50_unit,self.inhibit_max,MW=self.cmpbatch_id.full_mw,gtShift=3,drMax2=40)

#
# Assay (?)
# AssayData_SynMIC
# AssayData_SynIsobol
#
#